### PR TITLE
Fix cross-tenant RoleAssignment refresh

### LINKED ISSUE #4339: `azure-native:authorization:RoleAssignment` deletes cross-tenant assignments during refresh
### What happened?

`azure-native:authorization:RoleAssignment` supports **cross-tenant** role assignments via the [`DelegatedManagedIdentityResourceId`](https://www.pulumi.com/registry/packages/azure-native/api-docs/authorization/roleassignment/#delegatedmanagedidentityresourceid_csharp) field. This works as expected during creation. For **refresh**, the provider fails to detect the RoleAssignment and so removes the existing assignment from state.

### Example

TODO

### Output of `pulumi about`

TODO

### Additional context

This comes from a customer: https://pulumi.slack.com/archives/C9SGX9QA1/p1759920770752029 (internal link).

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by EronWright**
## Summary

Fixes #4339

Cross-tenant role assignments (those with `delegatedManagedIdentityResourceId`) were being removed from state during refresh operations. This PR implements a custom resource handler that properly reads cross-tenant role assignments by including the required `tenantId` query parameter.

## Root Cause

The Azure REST API has an asymmetry between creating and reading cross-tenant role assignments:

**Creating (PUT)** - Works correctly:
```
PUT /{scope}/roleAssignments/{name}?api-version=2022-04-01
Body: { "properties": { "delegatedManagedIdentityResourceId": "..." } }
```

**Reading (GET)** - Fails without tenantId:
```
GET /{scope}/roleAssignments/{name}?api-version=2022-04-01
❌ Returns 404 because tenantId query parameter is missing
```

The correct read operation needs:
```
GET /{scope}/roleAssignments/{name}?api-version=2022-04-01&tenantId={tenantId}
```

## Solution

Implemented a custom resource handler for `azure-native:authorization:RoleAssignment` that:

1. **Detects cross-tenant scenarios** by checking for `delegatedManagedIdentityResourceId` in inputs
2. **Extracts subscription ID** from the delegated identity resource ID using regex
3. **Retrieves tenant ID** by calling Azure Subscriptions API (`GET /subscriptions/{id}`)
4. **Includes tenantId** as a query parameter when reading the role assignment
5. **Falls back** to standard behavior for same-tenant assignments

## Implementation Details

**New file**: `provider/pkg/resources/customresources/custom_roleassignment.go`
- Custom Read function that intercepts role assignment reads
- Uses `armsubscriptions.Client` to look up tenant ID
- Maintains backwards compatibility

**Modified**: `provider/pkg/resources/customresources/customresources.go`
- Registered the custom resource in `BuildCustomResources`

**Dependencies**: Added `github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/resources/armsubscriptions`

### Unit Tests

Added comprehensive unit tests in `provider/pkg/resources/customresources/custom_roleassignment_test.go`:
- Tests cross-tenant role assignment read with tenantId parameter
- Tests same-tenant role assignment (standard behavior)
- Tests malformed delegated identity resource ID handling

### Integration Example

Added a new example in `examples/roleassignments/` demonstrating both scenarios:

**Scenario 1: Standard role assignment**
```typescript
const testUserAssignment = new authorization.RoleAssignment("testUserAssignment", {
    roleDefinitionId: pulumi.interpolate`${resourceGroup.id}/providers/Microsoft.Authorization/roleDefinitions/${reportsReaderRoleId}`,
    principalId: "e61877e9-d26b-4890-9a3c-2287e77ca427", // testuser
    principalType: authorization.PrincipalType.User,
    scope: resourceGroup.id,
});
```

**Scenario 2: Cross-tenant assignment (optional)**
```typescript
const crossTenantAssignment = delegatedIdentityResourceId && delegatedIdentityPrincipalId
    ? new authorization.RoleAssignment("crossTenantAssignment", {
        roleDefinitionId: pulumi.interpolate`${resourceGroup.id}/providers/Microsoft.Authorization/roleDefinitions/${reportsReaderRoleId}`,
        principalId: delegatedIdentityPrincipalId,
        principalType: authorization.PrincipalType.ServicePrincipal,
        scope: resourceGroup.id,
        delegatedManagedIdentityResourceId: delegatedIdentityResourceId,
    })
    : undefined;
```

The example includes:
- Complete TypeScript implementation (`examples/roleassignments/index.ts`)
- Comprehensive README with setup instructions
- Integration test (`TestRoleAssignmentsTs` in `examples/examples_nodejs_test.go`)
- Successfully validates create, refresh, and destroy operations

## Related Work

This solution mirrors the approach used by [terraform-provider-azurerm](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/authorization/role_assignment_resource.go), which stores the tenant ID in the resource ID using a pipe delimiter. Our approach avoids modifying the ID format while achieving the same result.

## References

- [Azure Role Assignments GET API](https://learn.microsoft.com/en-us/rest/api/authorization/role-assignments/get?view=rest-authorization-2022-04-01) - documents the `tenantId` parameter
- [Azure Subscriptions GET API](https://learn.microsoft.com/en-us/rest/api/resources/subscriptions/get) - used to retrieve tenant ID
- [delegatedManagedIdentityResourceId concept](https://learn.microsoft.com/en-us/azure/azure-resource-manager/managed-applications/concepts-delegated-managed-identity-resource-id)
- [Terraform's implementation](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/authorization/role_assignment_resource.go)

### CODE REVIEW

File: provider/pkg/resources/customresources/custom_roleassignment.go [hunk 1]
```diff
@@ -0,0 +1,176 @@
...
+	}
+
+	return *resp.Subscription.TenantID, nil
+}
+
+func (c *roleAssignmentClientImpl) convertResponseToOutputs(response map[string]any) map[string]any {
+	return c.crudClient.ResponseBodyToSdkOutputs(response)
+}
+
+// roleAssignment returns a custom resource for RoleAssignment that handles cross-tenant scenarios.
```
Comment (blampe) [inline provider/pkg/resources/customresources/custom_roleassignment.go]: Just to clarify, this create/read asymmetry is only an issue with these RoleAssignment resources specifically?

Comment (EronWright) [reply provider/pkg/resources/customresources/custom_roleassignment.go]: To my knowledge, yes.

I suppose one could survey for `tenantId` query parameter, maybe in the Authorization service specifically.  Will take a look now.
