### PR TITLE
Custom delete for dbforpostgresql:Configuration to reset to the correct default

### LINKED ISSUE #3476: Unable to delete an `azure-native.dbforpostgresql.Configuration` resource: PUT vs PATCH
### What happened?

I seem not to be able to delete an `azure-native.dbforpostgresql.Configuration` resource. As a consequence I can also not destroy a stack without manual intervention. As you can see in the reproducible example below I am only doing a minor configuration change.

Thank you for your great work on this project.

### Example

```ts
// index.ts

import {
  Configuration,
  Server,
  SkuTier,
} from "@pulumi/azure-native/dbforpostgresql";
import { ResourceGroup } from "@pulumi/azure-native/resources";

const resourceGroup = new ResourceGroup(`deleteme`);

const server = new Server(
  `deleteme`,
  {
    resourceGroupName: resourceGroup.name,
    administratorLogin: "NotForProduction",
    administratorLoginPassword: "NotForProduction",
    sku: {
      name: "Standard_B1ms",
      tier: SkuTier.Burstable,
    },
    version: "16",
    storage: {
      storageSizeGB: 32,
    },
  },
  { parent: resourceGroup },
);

new Configuration(
  "deleteme",
  {
    resourceGroupName: resourceGroup.name,
    serverName: server.name,
    configurationName: "azure.extensions",
    value: "vector",
    source: "user-override",
  },
  { parent: server },
);
```

```bash
root@c38eaf6a2211:/dev/workspace/pulumi/bugs# pulumi up
Please choose a stack, or create a new one: <create a new stack>
Please enter your desired stack name: dev 
Created stack 'dev'
Previewing update (dev):
     Type                                                 Name      Plan       Info
 +   pulumi:pulumi:Stack                                  bugs-dev  create     1 message
 +   └─ azure-native:resources:ResourceGroup              deleteme  create     
 +      └─ azure-native:dbforpostgresql:Server            deleteme  create     
 +         └─ azure-native:dbforpostgresql:Configuration  deleteme  create     

Diagnostics:
  pulumi:pulumi:Stack (bugs-dev):
    Downloading provider: azure-native

Resources:
    + 4 to create

Do you want to perform this update? yes
Updating (dev):
     Type                                                 Name      Status             
 +   pulumi:pulumi:Stack                                  bugs-dev  created (391s)     
 +   └─ azure-native:resources:ResourceGroup              deleteme  created (1s)       
 +      └─ azure-native:dbforpostgresql:Server            deleteme  created (363s)     
 +         └─ azure-native:dbforpostgresql:Configuration  deleteme  created (17s)      

Resources:
    + 4 created

Duration: 6m33s
```

I have verified that the configuration change has happened in Azure.

After commenting out the `Configuration` code block and running `pulumi up` I get the following error:

```bash
root@c38eaf6a2211:/dev/workspace/pulumi/bugs# pulumi up
Previewing update (dev):
     Type                                                 Name      Plan       
     pulumi:pulumi:Stack                                  bugs-dev             
     └─ azure-native:resources:ResourceGroup              deleteme             
        └─ azure-native:dbforpostgresql:Server            deleteme             
 -         └─ azure-native:dbforpostgresql:Configuration  deleteme  delete     

Resources:
    - 1 to delete
    3 unchanged

Do you want to perform this update? yes
Updating (dev):
     Type                                                 Name      Status                  Info
     pulumi:pulumi:Stack                                  bugs-dev  **failed**              1 error
     └─ azure-native:resources:ResourceGroup              deleteme                          
        └─ azure-native:dbforpostgresql:Server            deleteme                          
 -         └─ azure-native:dbforpostgresql:Configuration  deleteme  **deleting failed**     1 error

Diagnostics:
  azure-native:dbforpostgresql:Configuration (deleteme):
    error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '38555a33-74b0-4a0c-86ad-34b644d0ee0f'"

  pulumi:pulumi:Stack (bugs-dev):
    error: update failed

Resources:
    3 unchanged

Duration: 7m42s
```

The same also happens when running `pulumi destroy`.

### Output of `pulumi about`

```bash
root@c38eaf6a2211:/dev/workspace/pulumi/bugs# pulumi about
CLI          
Version      3.127.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  unknown

Host     
OS       debian
Version  12.6
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v20.16.0'

Current Stack: organization/bugs/dev

TYPE                                        URN
pulumi:pulumi:Stack                         urn:pulumi:dev::bugs::pulumi:pulumi:Stack::bugs-dev
pulumi:providers:azure-native               urn:pulumi:dev::bugs::pulumi:providers:azure-native::default_2_45_0
azure-native:resources:ResourceGroup        urn:pulumi:dev::bugs::azure-native:resources:ResourceGroup::deleteme
azure-native:dbforpostgresql:Server         urn:pulumi:dev::bugs::azure-native:resources:ResourceGroup$azure-native:dbforpostgresql:Server::deleteme
azure-native:dbforpostgresql:Configuration  urn:pulumi:dev::bugs::azure-native:resources:ResourceGroup$azure-native:dbforpostgresql:Server$azure-native:dbforpostgresql:Configuration::deleteme


Found no pending operations associated with dev

Backend        
Name           c38eaf6a2211
URL            azblob://pulumi-state?storage_account=plmiprodst6fe3d9bd
User           root
Organizations  
Token type     personal

Pulumi locates its logs in /tmp by default
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by thomas11**
Resolves #3476.

The `dbforpostgresql:Configuration` resource cannot actually be deleted, so we reset it to its default value instead. However, there are many configuration parameters with different defaults. On delete, we first GET this configuration to read the correct default value, then set it. This is the same approach that `az` takes in `az postgres flexible-server parameter set`.

### CODE REVIEW

File: sdk/dotnet/DBforPostgreSQL/Configuration.cs [hunk 1]
```diff
@@ -127,9 +127,6 @@ private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions?
                 Version = Utilities.Version,
                 Aliases =
                 {
-                    new global::Pulumi.Alias { Type = "azure-native:dbforpostgresql/v20200214preview:Configuration" },
-                    new global::Pulumi.Alias { Type = "azure-native:dbforpostgresql/v20200214privatepreview:Configuration" },
-                    new global::Pulumi.Alias { Type = "azure-native:dbforpostgresql/v20210410privatepreview:Configuration" },
```
Comment (danielrbradley) [inline sdk/dotnet/DBforPostgreSQL/Configuration.cs:132]: These look fine because these resources don't actually exist in the SDK. This is because these are listed in the `v2-removed-resources.json` file

https://github.com/pulumi/pulumi-azure-native/blob/0d0261fd754ec20a98c1b6336897d6935bd0cceb/versions/v2-removed-resources.json#L2660-L2661

**Review by danielrbradley — APPROVED** [review]

File: provider/pkg/gen/schema.go [hunk 2]
```diff
@@ -970,6 +970,10 @@ func (g *packageGenerator) genResourceVariant(apiSpec *openapi.ResourceSpec, res
 	return nil
 }
 
+func isSingleton(resource *resourceVariant) bool {
+	return resource.PathItem.Delete == nil || customresources.IsSingleton(resource.Path)
+}
```
Comment (danielrbradley) [inline provider/pkg/gen/schema.go:975]: This might be a nice place to explain what a singleton is

```suggestion
// isSingleton indicates if the resource is created and therefore deleted as
// part of its parent resource. When deleting a singleton we will reset its
// properties back to a default state. However a custom resource might still
// provide a delete method to perform a custom reset.
func isSingleton(resource *resourceVariant) bool {
	return resource.PathItem.Delete == nil || customresources.IsSingleton(resource.Path)
}
```

File: provider/pkg/resources/customresources/customresources.go [hunk 3]
```diff
@@ -229,6 +240,13 @@ func HasCustomDelete(path string) bool {
 	return false
 }
 
+func IsSingleton(path string) bool {
+	if res, ok := featureLookup[path]; ok {
```
Comment (danielrbradley) [inline provider/pkg/resources/customresources/customresources.go:244]: Ugh .. I find this magic global state for `featureLookup` lookup somewhat confusing. I think it was added for easier access at runtime in the provider .. but I guess this is fine to call to call during codegen too.

**Review by danielrbradley — APPROVED** [review]
Yup, this looks fine with the new singleton handling 👍
