### PR TITLE
Use correct cloud environment in azcore client

### LINKED ISSUE #3795: New AzCore API Breaks Environment
### What happened?

Hello,

I was previously using `v2.60.0` of the Azure Native plugin with Azure Government with success but recently decided decided to bump up to the latest `v2.77.0` and noticed that all my CI builds were failing.
Image

I started investigating and found that in the `v2.71.0` release notes there is mention of a new AzCore backend for the API that has been enabled by default and it notes instructions to disable it to fall back to the previous implementation.
After finding that and disabling the new AzCore backend, my builds are working again.

It appears that the new AzCore API changes are not respecting the `ARM_ENVIRONMENT` / `azure-native:environment` settings as it is clearly dialing the Azure Commercial endpoints instead of the Government ones.

### Example

1. Use an Azure Government environment
2. Specify `azure-native:environment` in the Pulumi config for the stack
3. `pulumi up`
    - explosions.

### Output of `pulumi about`

Image

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by thomas11**
When instantiating the new azcore-based Azure client, the cloud environment (public, usgov, etc.) was looked up in a wrong way. Since it defaults to "public", it didn't error and worked for most users. This PR refactors and adds more tests for more solid coverage.

Fixes #3795.

### CODE REVIEW

File: provider/pkg/provider/auth.go [hunk 1]
```diff
@@ -29,6 +32,26 @@ type authConfig struct {
...
+			return azureEnv.Environment{}, errors.Wrapf(err, "environment %q was not found", envName)
+		}
+	}
+	return env, nil
+}
+
+func (a *authConfig) cloud() azcloud.Configuration {
+	cloudName := "public"
+	if a.Config != nil && a.Config.Environment != "" {
+		cloudName = a.Environment
```
Comment (VenelinMartinov) [inline provider/pkg/provider/auth.go:50]: Did you mean `a.Config.Environment` here?

**Review by VenelinMartinov — APPROVED** [review]
Thanks for adding the tests, lgtm!

One possible typo.

File: provider/pkg/provider/auth.go [hunk 2]
```diff
@@ -29,6 +32,26 @@ type authConfig struct {
 	useCli bool
 }
 
+func (a *authConfig) autorestEnvironment() (azureEnv.Environment, error) {
+	envName := a.Environment
+	env, err := azureEnv.EnvironmentFromName(envName)
+	if err != nil {
+		env, err = azureEnv.EnvironmentFromName(fmt.Sprintf("AZURE%sCLOUD", envName))
```
Comment (flostadler) [inline provider/pkg/provider/auth.go:39]: It seems like they're planning to deprecate that format to some extent. They have a `//TODO: deprecate` comment next to `AZUREUSGOVERNMENTCLOUD`. https://github.com/Azure/go-autorest/blob/f7ea664c9cff3a5257b6dbc4402acadfd8be79f1/autorest/azure/environments.go#L38C3-L39

I only found https://github.com/Azure/go-autorest/issues/624 which seems to allude to them not being able to change it any time soon

**Review by flostadler — APPROVED** [review]
Looks good to me!

File: provider/pkg/provider/auth.go (hunk 1 above)
Comment (thomas11) [reply provider/pkg/provider/auth.go]: The two are actually the same, `Config` is an embedded struct. I've updated it to avoid this ambiguity.

File: provider/pkg/provider/auth.go (hunk 2 above)
Comment (thomas11) [reply provider/pkg/provider/auth.go:39]: We're actually going to remove this whole code soon-ish, since Autorest is deprecated.
