### PR TITLE
Retry Conflicts for AnotherOperationInProgress

### LINKED ISSUE #903: Retry "AnotherOperationInProgress" error messages
## Affected feature

Currently if Azure generates a "AnotherOperationInProgress" error Pulumi will fail. This error is often caused by trying to access two sub-resources on a resource at the same time. A good example is creating multiple subnets on a virtual network. Pulumi will try and create them all that the same time, but Azure can only create them one at a time.

Adding a back-off and retry for the "AnotherOperationInProgress" error message would help workaround this problem

### PR DESCRIPTION
**Pull request by danielrbradley**
The new azclient allows us to pass a callback function to decide if we want to retry a request. The default behaviour is to only retry a specific set of status codes. This extends that behaviour to also check Conflict (409) and retry if the "error.code" field is "AnotherOperationInProgress".

We're avoiding retrying all conflict status codes because some won't be fixed with a retry, so we're targeting the specific case instead.

Tested this both manually stepping through the code with a debugger and also created an integration test which previously failed but now passes when configured to use the new azclient instead of autorest client.

To access this improved behaviour right now, set the environment variable `PULUMI_ENABLE_AZCORE_BACKEND=true`. This will become the default in the future, but is currently in testing behind a feature flag.

This should address #903 which we will close once we've defaulted to using the new azcore implementation:
- https://github.com/pulumi/pulumi-azure-native/pull/3654

### CODE REVIEW

**Comment by thomas11** [comment]
Note that the feature toggle variable has been renamed to `PULUMI_ENABLE_AZCORE_BACKEND`.

**Comment by danielrbradley** [comment]
> Note that the feature toggle variable has been renamed to `PULUMI_ENABLE_AZCORE_BACKEND`.

This code path still seems to use the variable I'm referencing: https://github.com/pulumi/pulumi-azure-native/blob/6a41396ffd60f1d2647fe14e76dbb291baa18258/provider/pkg/provider/provider.go#L240

File: provider/pkg/azure/client_azcore.go [hunk 1]
```diff
@@ -61,6 +62,41 @@ func NewAzCoreClient(tokenCredential azcore.TokenCredential, userAgent string, a
...
+			// Check body for {"error":{"code":"AnotherOperationInProgress"}}
+			body, err := runtime.Payload(resp)
+			if err != nil {
+				return false
+			}
+			var errorBody map[string]interface{}
+			if err := json.Unmarshal(body, &errorBody); err != nil {
+				return false
+			}
+			if error, ok := errorBody["error"].(map[string]interface{}); ok {
```
Comment (thomas11) [inline provider/pkg/azure/client_azcore.go:90]: I didn't know this was possible in Go. The type conversion doesn't panic even when there's no "error" key in the map?

File: provider/pkg/azure/client_azcore.go [hunk 2]
```diff
@@ -61,6 +62,41 @@ func NewAzCoreClient(tokenCredential azcore.TokenCredential, userAgent string, a
...
+	// These are the same as the default values in sdk/azcore/runtime/policy_retry.go setDefaults
+	retryableStatusCodes := []int{
+		http.StatusRequestTimeout,      // 408
+		http.StatusTooManyRequests,     // 429
+		http.StatusInternalServerError, // 500
+		http.StatusBadGateway,          // 502
+		http.StatusServiceUnavailable,  // 503
+		http.StatusGatewayTimeout,      // 504
+	}
+	opts.Retry.ShouldRetry = func(resp *http.Response, err error) bool {
```
Comment (thomas11) [inline provider/pkg/azure/client_azcore.go:74]: A unit test for ShouldRetry would be good.

**Comment by thomas11** [comment]
> > Note that the feature toggle variable has been renamed to `PULUMI_ENABLE_AZCORE_BACKEND`.
> 
> This code path still seems to use the variable I'm referencing:
> 
> https://github.com/pulumi/pulumi-azure-native/blob/6a41396ffd60f1d2647fe14e76dbb291baa18258/provider/pkg/provider/provider.go#L240

Yes, the rename is in a PR #3630 that will be merged shortly (I hope).

**Comment by danielrbradley** [comment]
> Yes, the rename is in a PR #3630 that will be merged shortly (I hope).

Ok, happy to wait for that to go in, update this, then merge.

File: provider/pkg/azure/client_azcore.go (hunk 2 above)
Comment (danielrbradley) [reply provider/pkg/azure/client_azcore.go:75]: Gone with extracting the complex bit and unit testing that.

File: provider/pkg/azure/client_azcore.go (hunk 1 above)
Comment (danielrbradley) [reply provider/pkg/azure/client_azcore.go]: Reworked this to use structs which are easier to reason about.

File: provider/pkg/azure/client_azcore.go [hunk 3]
```diff
@@ -61,6 +62,32 @@ func NewAzCoreClient(tokenCredential azcore.TokenCredential, userAgent string, a
...
+		http.StatusServiceUnavailable,  // 503
+		http.StatusGatewayTimeout,      // 504
+	}
+
+	opts.Retry.ShouldRetry = func(resp *http.Response, err error) bool {
+		if err != nil {
+			return true
+		}
+		// Replicate default retry behaviour first.
+		if runtime.HasStatusCode(resp, retryableStatusCodes...) {
```
Comment (mikhailshilkov) [inline provider/pkg/azure/client_azcore.go:80]: Is there no way to literally call the old retry function instead of duplicating the logic?

File: provider/pkg/azure/client_azcore.go [hunk 4]
```diff
@@ -76,6 +103,24 @@ func NewAzCoreClient(tokenCredential azcore.TokenCredential, userAgent string, a
 	}, nil
 }
 
+func shouldRetryConflict(resp *http.Response) bool {
+	if runtime.HasStatusCode(resp, http.StatusConflict) {
+		// Check body for {"error":{"code":"AnotherOperationInProgress"}}
+		body, err := runtime.Payload(resp)
```
Comment (mikhailshilkov) [inline provider/pkg/azure/client_azcore.go:109]: Could we use https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/internal/exported/response_error.go#L23 instead? It looks like it's doing a similar parsing?

File: provider/pkg/azure/client_azcore.go (hunk 3 above)
Comment (danielrbradley) [reply provider/pkg/azure/client_azcore.go:80]: Nope, it's not actually a standalone function. It's just inline within the main retry implementation: https://github.com/Azure/azure-sdk-for-go/blob/068ef3d103a28dbd9657573091ccab7b5caca775/sdk/azcore/runtime/policy_retry.go#L179-L190

And the default status codes are defined here, but the setDefaults method isn't available either. The defaults are also only set on the internal copy of the struct so we can't just reference them from the opts object:
https://github.com/Azure/azure-sdk-for-go/blob/068ef3d103a28dbd9657573091ccab7b5caca775/sdk/azcore/runtime/policy_retry.go#L48-L58

File: provider/pkg/azure/client_azcore.go (hunk 4 above)
Comment (danielrbradley) [reply provider/pkg/azure/client_azcore.go:109]: Guess we could, but the we get back an untyped error which we have to try-cast into a `ResponseError` to access the `ErrorCode` field. I think what's here is a little easier to follow and has less magic.

Comment (mikhailshilkov) [reply provider/pkg/azure/client_azcore.go:109]: What's magical about casting to `ResponseError`? I feel like deserializing into an arbitrary structure is more bespoke.

**Review by thomas11 — APPROVED** [review]
I like the ResponseError suggestion and would try to use it. But approving since the current version also LGTM.

File: provider/pkg/azure/client_azcore.go (hunk 4 above)
Comment (danielrbradley) [reply provider/pkg/azure/client_azcore.go:109]: I guess it being called `NewResponseError` indicates it _really_ should be of type ResponseError .. and they shouldn't change the concrete type beneath us in the future. So guess it's probably fine. Also, yes looks like it handles the case of it being XML too.

**Comment by danielrbradley** [comment]
Squashed, rebased and switch PULUMI_USE_AUTOREST to PULUMI_ENABLE_AZCORE_BACKEND in the test
