### PR TITLE
Don't delete Service Plan when deleting last Web App

### LINKED ISSUE #1529: Destroying web app also destroys service plan
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When removing the last web app in an app service plan, the service plan is also deleted.
So, if the service plan was created from another stack, then that stack needs to be refreshed and re-applied before the apps can be brought back.
Looking at the documentation [here](https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/delete#uri-parameters), I am wondering if Pulumi should be specifying `deleteEmptyServerFarm=false` when talking to the REST API.

### Steps to reproduce

1. Create a stack with a service plan and web app.
2. Pulumi up.
2. Remove the web app, leaving the service plan.
3. Pulumi up.

Expected result: the service plan still exists in Azure.
Actual result: the service plan was automatically removed from Azure.

### PR DESCRIPTION
**Pull request by thomas11**
Resolves #1529 

By default, when deleting the only Web App in a Service Plan, Azure deletes the Service Plan as well. This doesn't mesh with the Pulumi resource model since the Service Plan is a separate resource.

The default Azure behavior can be customized with a query parameter `deleteEmptyServerFarm` on the DELETE request. However, so far we don't have any support for delete parameters. I saw two ways of approaching this:
1. Add support for delete parameters to the schema, and pass them through so that the regular delete operation in the provider does the right thing.
2. Implement a custom resource for Web App, with only the delete method, re-using as much provider code as possible.

The problem with (1) is that it would expose the `deleteEmptyServerFarm` parameter via the schema but we'd still not know which value it would be set to without custom handling for the Web App case. This PR implements approach (2). I'm open to changing course, though.

In order to be able to re-use the provider's existing delete logic, the required methods are encapsulated in a new interface `AzureClient` which can be passed to the custom resources factory. This will probably also be useful to support POST-based operations, as it would be simple to add the `azurePost` method to the interface and call it from custom resources.

Tests are still TODO, but this PR fixed the issue for me in a local, manual test.

### CODE REVIEW

File: provider/pkg/resources/custom_webapp_delete_test.go [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+
+func (t *TestAzureClient) AzureDelete(ctx context.Context, id, apiVersion, asyncStyle string, queryParams map[string]any) error {
+	t.queryParamsOfLastDelete = queryParams
+	return nil
+}
+
+func TestSetsDeleteParam(t *testing.T) {
+	client := TestAzureClient{}
+	custom := customWebAppDelete(&client)
+	custom.Delete(context.TODO(), "id", resource.PropertyMap{})
```
Comment (blampe) [inline provider/pkg/resources/custom_webapp_delete_test.go:27]:
```suggestion
	custom.Delete(context.Background(), "id", resource.PropertyMap{})
```

File: provider/pkg/resources/custom_webapp_delete_test.go [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+
+import (
+	"context"
+	"testing"
+
+	"github.com/pulumi/pulumi/sdk/v3/go/common/resource"
+	"github.com/stretchr/testify/assert"
+)
+
+type TestAzureClient struct {
```
Comment (blampe) [inline provider/pkg/resources/custom_webapp_delete_test.go:11]: Nice mock!

File: provider/pkg/resources/custom_webapp_delete.go [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+	"fmt"
+
+	"github.com/pulumi/pulumi/sdk/v3/go/common/resource"
+)
+
+const webAppResourceType = "azure-native:web:WebApp"
+
+// https://github.com/pulumi/pulumi-azure-native/issues/1529
+func customWebAppDelete(azureClient AzureClient) *CustomResource {
+	return &CustomResource{
```
Comment (blampe) [inline provider/pkg/resources/custom_webapp_delete.go:14]: I assume this falls back on upstream create/update/etc?

**Review by blampe — APPROVED** [review]
Looks reasonable, only a small suggestion re: the interface.

File: provider/pkg/resources/customresources.go [hunk 4]
```diff
@@ -16,6 +16,11 @@ import (
 	"github.com/pulumi/pulumi/sdk/v3/go/common/resource"
 )
 
+type AzureClient interface {
+	LookupResource(resourceType string) (AzureAPIResource, bool, error)
+	AzureDelete(ctx context.Context, id, apiVersion, asyncStyle string, queryParams map[string]any) error
+}
```
Comment (blampe) [inline provider/pkg/resources/customresources.go:22]: Agree this could be helpful for POSTs and elsewhere, but if you extended this to another method like `Create` it doesn't make sense for tests to need to implement `AzureDelete`. I suggest splitting this into a some smaller interfaces so you can mix and match only the things you need:

```
type Lookupper interface {
    Lookup(resourceType string) (AzureAPIResource, bool, error)
}

type Deleter interface {
	Delete(ctx context.Context, id, apiVersion, asyncStyle string, queryParams map[string]any) error}
}

type LookupDeleter interface {
    Lookupper
    Deleter
}
```

File: provider/pkg/resources/custom_webapp_delete.go (hunk 3 above)
Comment (thomas11) [reply provider/pkg/resources/custom_webapp_delete.go:14]: correct

File: provider/pkg/resources/customresources.go (hunk 4 above)
Comment (thomas11) [reply provider/pkg/resources/customresources.go]: Good point, thanks
