### PR TITLE
Custom support for File Share Protected Items

### LINKED ISSUE #1420: Backup a FileShare in a Recovery Services Vault
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I want to create a backup of a FileShare in a Recovery Services Vault. The last operation that link the fileShare to a specific backup Policy, `recoveryservices.ProtectedItem`, fail with the following error :

```text
azure-native:recoveryservices:ProtectedItem (recoveryservices-backup-fileshare-oto):
    error: resource partially created but read failed autorest/azure: Service returned an error. Status=404 Code="BMSUserErrorDataSourceObjectNotFound" Message="Item not found. Selected item might have been deleted. Please check if item is registered to the vault.": autorest/azure: Service returned an error. Status=404 Code="BMSUserErrorDataSourceObjectNotFound" Message="Item not found. Selected item might have been deleted. Please check if item is registered to the vault."
```

The `recoveryservices.ProtectedItem` is correctly created in Azure but Pulumi cannot find it after that. Going through the Pulumi debug output confirm that (See section below)

Querying Azure for this resource show a different name : `AzurefileShare;AF23B29A90AD83DB869CB1B21886E4FB91CA9309749F87A53614CA07DDE53D5D` (Azure)
instead of `AzurefileShare;otobackupconf` (Pulumi). I cannot figure out where does this name come from or how it is generated. 

```shell
az backup item list --resource-group rg-cloud-platform --vault-name recoveryservices-epa-dev
```

```json
{
    "eTag": null,
    "id": "/subscriptions/SUB_NAME/resourceGroups/rg-cloud-platform/providers/Microsoft.RecoveryServices/vaults/recoveryservices-epa-dev/backupFabrics/Azure/protectionContainers/StorageContainer;Storage;rg-epa-oto-vm-dev;saepaotobackupdev/protectedItems/AzureFileShare;AF23B29A90AD83DB869CB1B21886E4FB91CA9309749F87A53614CA07DDE53D5D",
    "location": null,
    "name": "AzureFileShare;AF23B29A90AD83DB869CB1B21886E4FB91CA9309749F87A53614CA07DDE53D5D",
    "properties": {
      "backupManagementType": "AzureStorage",
      "backupSetName": null,
      "containerName": "StorageContainer;Storage;rg-epa-oto-vm-dev;saepaotobackupdev",
      "createMode": null,
      "deferredDeleteTimeInUtc": null,
      "deferredDeleteTimeRemaining": null,
      "extendedInfo": null,
      "friendlyName": "otobackupconf",
      "healthStatus": null,
      "isArchiveEnabled": false,
      "isDeferredDeleteScheduleUpcoming": null,
      "isRehydrate": null,
      "isScheduledForDeferredDelete": null,
      "kpisHealths": {},
      "lastBackupStatus": "IRPending",
      "lastBackupTime": null,
      "lastRecoveryPoint": null,
      "policyId": "/subscriptions/SUB_NAME/resourceGroups/rg-cloud-platform/providers/Microsoft.RecoveryServices/vaults/recoveryservices-epa-dev/backupPolicies/protectionPolicy-epa-fileShare-dev",
      "protectedItemType": "AzureFileShareProtectedItem",
      "protectionState": "IRPending",
      "protectionStatus": "Healthy",
      "sourceResourceId": "/subscriptions/SUB_NAME/resourceGroups/rg-epa-oto-vm-dev/providers/Microsoft.Storage/storageAccounts/saepaotobackupdev",
      "workloadType": "AzureFileShare"
    },
    "resourceGroup": "rg-cloud-platform",
    "tags": null,
    "type": "Microsoft.RecoveryServices/vaults/backupFabrics/protectionContainers/protectedItems"
  }
```

When I create this resource in the Azure Portal, where I cannot specify a name, I got the same wrong name.

If I replace the property `protectedItemName` with the name `AzurefileShare;AF23B29A90AD83DB869CB1B21886E4FB91CA9309749F87A53614CA07DDE53D5D`, Pulumi can successfully deploy the stack.

```typescript
new recoveryservices.ProtectedItem(fileShareBackupToVaultName,
    {
        containerName : 'StorageContainer;Storage;rg-epa-oto-vm-dev;saepaotobackupdev',
        fabricName: 'Azure',
        properties: {
            backupManagementType: recoveryservices.BackupManagementType.AzureStorage,
            friendlyName: 'otobackupconf',
            policyId: '/subscriptions/SUB_NAME/resourceGroups/rg-cloud-platform/providers/Microsoft.RecoveryServices/vaults/recoveryservices-epa-dev/backupPolicies/protectionPolicy-epa-fileShare-dev',
            protectedItemType: 'AzureFileShareProtectedItem',
            sourceResourceId: '/subscriptions/SUB_NAME/resourceGroups/rg-epa-oto-vm-preprod/providers/Microsoft.Storage/storageAccounts/saepaotobackupdev',
            workloadType: recoveryservices.WorkloadType.AzureFileShare,
        },
        protectedItemName: 'AzurefileShare;AF23B29A90AD83DB869CB1B21886E4FB91CA9309749F87A53614CA07DDE53D5D', //`AzurefileShare;otobackupconf`,
        resourceGroupName: 'rg-cloud-platform',
        vaultName: 'recoveryservices-epa-dev',
    })
```

FileShare infos 
```json
[
  {
    "metadata": null,
    "name": "otobackupconf",
    "properties": {
      "etag": "\"0x8D9D43938EEB574\"",
      "lastModified": "2022-01-10T13:00:48+00:00",
      "quota": 128
    },
    "snapshot": null
  }
]
```

I am using the latest availables libs - @pulumi/pulumi@3.21.0 and @pulumi/azure-native@1.52.0.

## Debug output

```text
PUT [https://management.azure.com/subscriptions/SUB_NAME/resourceGroups/rg-cloud-platform/providers/Microsoft.RecoveryServices/vaults/recoveryservices-epa-dev/backupFabrics/Azure/protectionContainers/StorageContainer%3BStorage%3Brg-epa-oto-vm-dev%3Bsaepaotobackupdev/protectedItems/AzurefileShare%3Botobackupconf?api-version=2021-02-01
HTTP/1.1 202 Accepted
Content-Length: 0
Azure-Asyncoperation: https://management.azure.com/subscriptions/SUB_NAME/resourceGroups/rg-cloud-platform/providers/Microsoft.RecoveryServices/vaults/recoveryservices-epa-dev/backupFabrics/Azure/protectionContainers/StorageContainer;Storage;rg-epa-oto-vm-dev;saepaotobackupdev/protectedItems/AzurefileShare;otobackupconf/operationsStatus/0bcb1160-b209-48d6-aa5a-096f07abc85c?api-version=2021-02-01
Cache-Control: no-cache
Date: Mon, 10 Jan 2022 11:36:02 GMT
Expires: -1
Location: https://management.azure.com/subscriptions/SUB_NAME/resourceGroups/rg-cloud-platform/providers/Microsoft.RecoveryServices/vaults/recoveryservices-epa-dev/backupFabrics/Azure/protectionContainers/StorageContainer;Storage;rg-epa-oto-vm-dev;saepaotobackupdev/protectedItems/AzurefileShare;otobackupconf/operationResults/0bcb1160-b209-48d6-aa5a-096f07abc85c?api-version=2021-02-01
Pragma: no-cache
Retry-After: 60
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Client-Request-Id: 6759906b-eb80-45a5-bbaa-920289cad1c9
X-Ms-Client-Request-Id: 6759906b-eb80-45a5-bbaa-920289cad1c9
X-Ms-Correlation-Request-Id: 6f920e2c-5e7e-494b-8091-2563b98a2500
X-Ms-Ratelimit-Remaining-Subscription-Writes: 1199
X-Ms-Request-Id: 6f920e2c-5e7e-494b-8091-2563b98a2500
X-Ms-Routing-Request-Id: FRANCECENTRAL:20220110T113603Z:6f920e2c-5e7e-494b-8091-2563b98a2500
X-Powered-By: ASP.NET

===================================================
GET [https://management.azure.com/subscriptions/SUB_NAME/resourceGroups/rg-cloud-platform/providers/Microsoft.RecoveryServices/vaults/recoveryservices-epa-dev/backupFabrics/Azure/protectionContainers/StorageContainer;Storage;rg-epa-oto-vm-dev;saepaotobackupdev/protectedItems/AzurefileShare;otobackupconf/operationsStatus/0bcb1160-b209-48d6-aa5a-096f07abc85c?api-version=2021-02-01 
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: no-cache
Content-Type: application/json
Date: Mon, 10 Jan 2022 11:37:03 GMT
Expires: -1
Pragma: no-cache
Server: Microsoft-IIS/10.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Ms-Client-Request-Id: 4eee0fec-5c53-46de-b8b5-859a001b610d
X-Ms-Client-Request-Id: 4eee0fec-5c53-46de-b8b5-859a001b610d
X-Ms-Correlation-Request-Id: 1695fe1c-0e65-45ab-8bf1-b7b0d92fe929
X-Ms-Ratelimit-Remaining-Subscription-Resource-Requests: 149
X-Ms-Request-Id: 1695fe1c-0e65-45ab-8bf1-b7b0d92fe929
X-Ms-Routing-Request-Id: FRANCECENTRAL:20220110T113703Z:1695fe1c-0e65-45ab-8bf1-b7b0d92fe929
X-Powered-By: ASP.NET
130
{"id":"0bcb1160-b209-48d6-aa5a-096f07abc85c","name":"0bcb1160-b209-48d6-aa5a-096f07abc85c","status":"Succeeded","startTime":"2022-01-10T11:36:02.3423041Z","endTime":"2022-01-10T11:36:02.3423041Z","properties":{"objectType":"OperationStatusJobExtendedInfo","jobId":"64b65ebc-a641-47f6-bdc1-baa9bcdfbe32"}}
0

===================================================
GET [https://management.azure.com/subscriptions/SUB_NAME/resourceGroups/rg-cloud-platform/providers/Microsoft.RecoveryServices/vaults/recoveryservices-epa-dev/backupFabrics/Azure/protectionContainers/StorageContainer%3BStorage%3Brg-epa-oto-vm-dev%3Bsaepaotobackupdev/protectedItems/AzurefileShare%3Botobackupconf?api-version=2021-02-01 ===================================================
HTTP/1.1 404 Not Found
Content-Length: 173
Cache-Control: no-cache
Content-Type: application/json
Date: Mon, 10 Jan 2022 11:37:03 GMT
Pragma: no-cache
Server: Microsoft-IIS/10.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Client-Request-Id: 4e77ee85-f564-42eb-bc74-211cefa2c236
X-Ms-Client-Request-Id: 4e77ee85-f564-42eb-bc74-211cefa2c236
X-Ms-Correlation-Request-Id: 1f4cbfda-33e9-40b0-a5fd-612d7686e554
X-Ms-Ratelimit-Remaining-Subscription-Resource-Requests: 147
X-Ms-Request-Id: 1f4cbfda-33e9-40b0-a5fd-612d7686e554
X-Ms-Routing-Request-Id: FRANCECENTRAL:20220110T113703Z:1f4cbfda-33e9-40b0-a5fd-612d7686e554
X-Powered-By: ASP.NET
{"error":{"code":"BMSUserErrorDataSourceObjectNotFound","message":"Item not found. Selected item might have been deleted. Please check if item is registered to the vault."}}
```

### Steps to reproduce

1. Create Recovery Services Vault - `recoveryservices.Vault`
2. Create Backup Policy for FileShare - `recoveryservices.ProtectionPolicy`
3. Register Storage Account in the Vault - `recoveryservices.ProtectionContainer`
4. Create  - `recoveryservices.ProtectedItem`

Expected: Pulumi successful deployement
Actual: Pulumi cannot read the `recoveryservices.ProtectedItem` after creating it

### PR DESCRIPTION
**Pull request by thomas11**
Resolves #1420

_**Note**: the integration test succeeds in creating and deleting the resources under test. However, it fails at the end because the storage account cannot be deleted as it's locked. I wasn't yet able to figure out why or how to remove the lock._

The [recoveryservices.ProtectedItem](https://www.pulumi.com/registry/packages/azure-native/api-docs/recoveryservices/protecteditem/) represents a resource that's backed up via Azure Backup Service (which confusingly has the namespace Microsoft.RecoveryServices). ProtectedItem is a sort of union type with one member per Azure resource that can be protected, e.g., AzureVmWorkloadProtectedItem.

One of these types, AzureFileshareProtectedItem, is special in that it requires a file share name as input that's _not_ the name of the file share as given by the user and as shown by the portal, but an internal "system name". Therefore, attempting to use AzureFileshareProtectedItem in the standard way is not possible, because for file share "Foo", `"protectedItemName": "Foo"` will not work.

Instead, we need to look up the system name for the user-visible name "Foo" first, and use it instead.

~~My first attempt (branch `tkappler/tkappler/recoveryservices-1420`) was to implement a standard custom resource with custom CRUD methods that use the system name, after looking it up via the recoveryservices Azure SDK. That worked, but is a lot of custom code when the actual CRUD operations are completely standard, once the system name is known.~~

~~So in this PR I instead extended the CustomResource abstraction with a `PreCreate` method that modifies the user-given input when a resource is created. The name could be improved. This allows the provider to check if `PreCreate` is implemented for the current resource type, if yes, use it to transform the input, then carry on with the standard create code path. In this case, input~~

```json
  "protectedItemName": "Foo"
```

becomes, after `PreCreate` looks up the system name via the Azure SDK, 

```json
{
  "protectedItemName": "azurefileshare;339f98592ed6329dc5f83bdbb8675bd3528bf58d2246d5e172615186febdc45c",
  "__friendlyProtectedItemName": "Foo"
}
```

~~When the ProtectedItem to be created is not a File Share, `PreCreate` does nothing.~~

### CODE REVIEW

File: examples/recoveryservices-protecteditem/index.ts [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+                retentionDuration: {
+                    count: 30,
+                    durationType: 'Days',
+                },
+                retentionTimes: ['2024-10-08T19:30:00Z'],
+            },
+        },
+        timeZone: 'GTB Standard Time',
+        workLoadType: recoveryservices.WorkloadType.AzureFileShare,
+    } // as recoveryservicesTypes.input.recoveryservices.AzureFileShareProtectionPolicyArgs,
```
Comment (mjeffryes) [inline examples/recoveryservices-protecteditem/index.ts:68]: Stray comment?

File: examples/recoveryservices-protecteditem/index.ts [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+
+// Enable backup for Azure File Share (Protected Item)
+const protectedItem = new recoveryservices.ProtectedItem('protectedItem', {
+    containerName: protectionContainer.name,
+    fabricName: 'Azure',
+    properties: {
+        policyId: protectionPolicy.id,
+        protectedItemType: 'AzureFileShareProtectedItem',
+        sourceResourceId: storageAccount.id,
+    }, // as recoveryservicesTypes.input.recoveryservices.AzureFileshareProtectedItemArgs,
```
Comment (mjeffryes) [inline examples/recoveryservices-protecteditem/index.ts:102]: another one?

File: examples/recoveryservices-protecteditem/index.ts [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+const storageAccount = new storage.StorageAccount('sa', {
+    resourceGroupName: resourceGroup.name,
+    location: resourceGroup.location,
+    kind: 'StorageV2',
+    sku: {
+        name: 'Standard_LRS',
+    },
+    publicNetworkAccess: 'Enabled',
+}, {
+    dependsOn: [vault],
```
Comment (mjeffryes) [inline examples/recoveryservices-protecteditem/index.ts:42]: curious, why does the storage account depend on vault?

File: examples/recoveryservices-protecteditem/graph2.dot [hunk 4]
```diff
@@ -0,0 +1,35 @@
+strict digraph {
```
Comment (mjeffryes) [inline examples/recoveryservices-protecteditem/graph2.dot]: leftover from debugging?

File: provider/pkg/provider/provider.go [hunk 5]
```diff
@@ -932,6 +932,15 @@ func (k *azureNativeProvider) Create(ctx context.Context, req *rpc.CreateRequest
 		}, nil
 	}
 
+	customRes, isCustom := k.customResources[res.Path]
```
Comment (mjeffryes) [inline provider/pkg/provider/provider.go:935]: probably worth a comment explaining why this is here?

File: provider/pkg/resources/customresources/customresources.go [hunk 6]
```diff
@@ -58,6 +58,9 @@ type CustomResource struct {
 	// to our custom shape and behavior. Optional.
 	// Deprecated: Use Schema instead.
 	MetaTypeOverrides map[string]AzureAPIType
+	// PreCreate is a function that is called to modify the input before the resource is created. Don't use in
+	// combination with Create; just modify the input inside Create in that scenario.
+	PreCreate func(ctx context.Context, input resource.PropertyMap) (resource.PropertyMap, error)
```
Comment (mjeffryes) [inline provider/pkg/resources/customresources/customresources.go:63]: This kind of feels like a design wart to have both this and create. 

It's good motivation for the functional redesign of customresource that @danielrbradley has pitched a few times so that they could be written as transformations on the generated resource rather than requiring a wholesale replace.

File: provider/pkg/resources/customresources/custom_recoveryservices.go [hunk 7]
```diff
@@ -0,0 +1,198 @@
...
+
+type systemNameReader interface {
+	readSystemNameFromProtectableItem(ctx context.Context, input *protectedItemProperties) (string, error)
+}
+
+type systemNameReaderImpl struct {
+	protectableItemsClient *recovery.BackupProtectableItemsClient
+}
+
+func (s *systemNameReaderImpl) readSystemNameFromProtectableItem(ctx context.Context, input *protectedItemProperties) (string, error) {
```
Comment (mjeffryes) [inline provider/pkg/resources/customresources/custom_recoveryservices.go:98]: nit. The `protectedItemProperties` is kind of a large bag of stuff (9 properties), where it only looks like you're using 4 properties. Might be cleaner to pass those values individually or make a more targeted input type.

It might also be worth writing unittests for just this method.

**Review by mjeffryes — APPROVED** [review]
I think we need to rethink the design of 
`CustomResource` a bit, but I'm eager to get something to the customer here so don't want to block on that.

RE the locked storage account, my quick search implies that the recoveryservice-protected item is probably adding a blob with a retention policy which is blocking the delete. I have no idea how you'd go about removing that, and that would obviously be the first choice. However, one workaround could be to just provision a well-known storage account in a separate stack that we leave up and just use it via stack references in the test.

File: examples/recoveryservices-protecteditem/index.ts (hunk 1 above)
Comment (thomas11) [reply examples/recoveryservices-protecteditem/index.ts:71]: I left those in to make clear which type we're instantiating here. With Typescript's automatically-resolved union types, it's possible to accidentally instantiate a wrong type when setting the wrong properties.

File: provider/pkg/resources/customresources/custom_recoveryservices.go (hunk 7 above)
Comment (thomas11) [reply provider/pkg/resources/customresources/custom_recoveryservices.go:113]: I pulled out the middle part and added unit tests for it. The parts using the Azure SDK are hard to test because the SDK types are plain structs 😞

**Review by danielrbradley — COMMENTED** [review]
Not 100% sure yet that mutating the input set is the right way to go here.

Mutating inputs is the job of the Check function. It's somewhat irregular for the Create or Update method to modify Inputs. That said, Check generally shouldn't do network calls as I think it's currently not run in parallel between resources and so is a performance bottleneck.

Going back to the reason we're needing to modify the inputs: as far as I can tell from the code, this is in order to fix the `protectedItemName` so that the `id` is generated correctly which is done external to the custom Create method and passed in.

A first alternate would be to not generate the `id` (and `queryParams`) before calling the custom Create method but instead pass the `crudClient` into the custom resource methods so the custom implementation can choose how to generate its own `id`.

A second alternative would be to allow custom resources to override specifically how they generate their own `id` (and perhaps `queryParams`). E.g. `GetIdAndQuery func(ctx context.Context, inputs resource.PropertyMap, crudClient crud.ResourceCrudClient) (string, map[string]any, error)`

**Review by danielrbradley — COMMENTED** [review]
Really happy with the overall implementation!

Two minor areas for improvements commented inline.

File: provider/pkg/resources/customresources/custom_recoveryservices.go [hunk 8]
```diff
@@ -0,0 +1,246 @@
...
+	if err != nil {
+		return "", nil, err
+	}
+
+	if systemName != "" {
+		lastSlashIndex := strings.LastIndex(origId, "/")
+		if lastSlashIndex != -1 {
+			origId = origId[:lastSlashIndex+1] + systemName
+		}
+	}
```
[the remark this answers is not in the document]
Comment (thomas11) [reply provider/pkg/resources/customresources/custom_recoveryservices.go]: Done (2)

**Comment by danielrbradley** [comment]
I see the unit test changed from:
```diff
- azurefileshare;339f9859
+ azurefileshare%3B339f9859
```
Was this just a typo or does the deep copy do some weird double encoding?

**Comment by thomas11** [comment]
> I see the unit test changed from:
> 
> ```diff
> - azurefileshare;339f9859
> + azurefileshare%3B339f9859
> ```
> 
> Was this just a typo or does the deep copy do some weird double encoding?

It's actually our `crudClient.PrepareAzureRESTIdAndQuery(inputsCopy)` that does it. It URL-encodes each parameter - which is correct and was wrong in the previous code. The Azure API seems to accept both forms.

**Review by danielrbradley — APPROVED** [review]
