### PR TITLE
Fix properties prefixed with numbers

### LINKED ISSUE #1528: Go code generation fails for property name starting with number
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

- Azure have released the `mobilenetwork` v2022-01-01-preview API spec.
- The `simPolicy.json` API defines a `DataNetworkConfiguration` object definition with a property called `5qi`.
- Attempting to generate the go SDK results in non-compilable go code.
- The process fails when trying to format the code before outputting it (and therefore we get no output files).

image

### PR DESCRIPTION
**Pull request by danielrbradley**
Fixes #1528

Following approach from https://github.com/pulumi/pulumi/blob/90913de3fbf1dac0908afda785149c83b27d7424/pkg/codegen/go/utilities.go#L81-L82 as suggested by @mikhailshilkov 

This might be solved in pulumi/pulumi as part of the SDK generation for incompatible names at some point.

### CODE REVIEW

File: provider/pkg/gen/utilities_test.go [hunk 1]
```diff
@@ -14,6 +14,8 @@ func TestToLowerCamel(t *testing.T) {
 		{"ID", "id"},
 		{"TTL", "ttl"},
 		{"_ref", "ref"},
+		{"5qi", "fiveqi"},
```
[the remark this answers is not in the document]
Comment (danielrbradley) [reply provider/pkg/gen/utilities_test.go:17]: Hmm, yeah, that looks better

File: provider/pkg/gen/utilities.go [hunk 2]
```diff
@@ -32,8 +47,13 @@ func ToLowerCamel(s string) string {
 	if uppercaseAcronym[s] {
 		s = strings.ToLower(s)
 	}
-	if r := rune(s[0]); r == '_' {
-		s = s[1:]
+	r := []rune(s)
+	if prefix, found := commonPrefixReplacements[r[0]]; found {
+		if len(r) > 1 {
+			s = prefix + strings.ToUpper(string(r[1])) + string(r[2:])
```
Comment (mikhailshilkov) [inline provider/pkg/gen/utilities.go:53]:
```suggestion
			s = prefix + strings.ToUpper(string(r[1])) + r[2:]
```
I think this may work

**Review by mikhailshilkov — APPROVED** [review]
LGTM

File: provider/pkg/gen/utilities.go (hunk 2 above)
Comment (danielrbradley) [reply provider/pkg/gen/utilities.go:53]: Nope .. `invalid operation: mismatched types string and []rune` - think it needs the explicit conversion

Comment (mikhailshilkov) [reply provider/pkg/gen/utilities.go:53]: How does this work then? https://github.com/pulumi/pulumi-azure-native/blob/95c2dc8b77fc3675ed8328374a1e18ee2af7608f/provider/pkg/gen/utilities.go#L59

Comment (mikhailshilkov) [reply provider/pkg/gen/utilities.go:53]: Ah, I missed `r := []rune(s)`! I see.
