### PR TITLE
[V2] Consistently title-case resource names

### LINKED ISSUE #2365: Inconsistent resource name casing in provider's schema
### What happened?

([context](https://pulumi.slack.com/archives/C02FXTZEZ6W/p1680934246894199))

In the Azure Native provider, I noticed that most of the resource names start with an upper case letter (`azure-native:advisor/v20160712preview:Suppression` => `Suppression`). This is nice because it correctly matches the name of resource in the TS/JS SDK.

However, for a few resources they seem to start with a lowercase letter (`azure-native:aadiam/v20200301preview:privateLinkForAzureAd` => `privateLinkForAzureAd`).

### Expected Behavior

I _think_ the resource name should start with an upper case letter (TitleCase) since the large majority follows the TitleCase.

### Steps to reproduce

Run the following command to list all resources with a lowercase resource name.

```bash
pulumi package get-schema azure-native@1.99.1 | jq -r '.resources | keys[]' | sed -n '/.*:.*:[a-z].*/p'
```

Here is the list of affected resources (68 resources)
```
azure-native:aadiam/v20200301:privateLinkForAzureAd
azure-native:aadiam/v20200301preview:privateLinkForAzureAd
azure-native:aadiam/v20200701preview:azureADMetric
azure-native:aadiam:azureADMetric
azure-native:aadiam:privateLinkForAzureAd
azure-native:azurestackhci/v20210701preview:galleryimageRetrieve
azure-native:azurestackhci/v20210701preview:networkinterfaceRetrieve
azure-native:azurestackhci/v20210701preview:virtualharddiskRetrieve
azure-native:azurestackhci/v20210701preview:virtualmachineRetrieve
azure-native:azurestackhci/v20210701preview:virtualnetworkRetrieve
azure-native:azurestackhci/v20210901preview:galleryimageRetrieve
azure-native:azurestackhci/v20210901preview:marketplacegalleryimage
azure-native:azurestackhci/v20210901preview:networkinterfaceRetrieve
azure-native:azurestackhci/v20210901preview:storagecontainerRetrieve
azure-native:azurestackhci/v20210901preview:virtualharddiskRetrieve
azure-native:azurestackhci/v20210901preview:virtualmachineRetrieve
azure-native:azurestackhci/v20210901preview:virtualnetworkRetrieve
azure-native:databricks/v20180401:vNetPeering
azure-native:databricks/v20210401preview:vNetPeering
azure-native:databricks/v20220401preview:vNetPeering
azure-native:databricks/v20230201:vNetPeering
azure-native:databricks:vNetPeering
azure-native:healthbot/v20201020:getbot
azure-native:healthbot/v20201020preview:getbot
azure-native:hybridcontainerservice/v20220501preview:agentPool
azure-native:hybridcontainerservice/v20220501preview:storageSpaceRetrieve
azure-native:hybridcontainerservice/v20220501preview:virtualNetworkRetrieve
azure-native:hybridcontainerservice:agentPool
azure-native:hybridcontainerservice:storageSpaceRetrieve
azure-native:hybridcontainerservice:virtualNetworkRetrieve
azure-native:insights/v20180601preview:guestDiagnosticsSetting
azure-native:insights:guestDiagnosticsSetting
azure-native:m365securityandcompliance/v20210325preview:privateLinkServicesForEDMUpload
azure-native:m365securityandcompliance/v20210325preview:privateLinkServicesForM365ComplianceCenter
azure-native:m365securityandcompliance/v20210325preview:privateLinkServicesForM365SecurityCenter
azure-native:m365securityandcompliance/v20210325preview:privateLinkServicesForMIPPolicySync
azure-native:m365securityandcompliance/v20210325preview:privateLinkServicesForO365ManagementActivityAPI
azure-native:m365securityandcompliance/v20210325preview:privateLinkServicesForSCCPowershell
azure-native:m365securityandcompliance:privateLinkServicesForEDMUpload
azure-native:m365securityandcompliance:privateLinkServicesForM365ComplianceCenter
azure-native:m365securityandcompliance:privateLinkServicesForM365SecurityCenter
azure-native:m365securityandcompliance:privateLinkServicesForMIPPolicySync
azure-native:m365securityandcompliance:privateLinkServicesForO365ManagementActivityAPI
azure-native:m365securityandcompliance:privateLinkServicesForSCCPowershell
azure-native:securityandcompliance/v20210111:privateLinkServicesForEDMUpload
azure-native:securityandcompliance/v20210111:privateLinkServicesForM365ComplianceCenter
azure-native:securityandcompliance/v20210111:privateLinkServicesForM365SecurityCenter
azure-native:securityandcompliance/v20210111:privateLinkServicesForO365ManagementActivityAPI
azure-native:securityandcompliance/v20210111:privateLinkServicesForSCCPowershell
azure-native:securityandcompliance/v20210308:privateLinkServicesForEDMUpload
azure-native:securityandcompliance/v20210308:privateLinkServicesForM365ComplianceCenter
azure-native:securityandcompliance/v20210308:privateLinkServicesForM365SecurityCenter
azure-native:securityandcompliance/v20210308:privateLinkServicesForMIPPolicySync
azure-native:securityandcompliance/v20210308:privateLinkServicesForO365ManagementActivityAPI
azure-native:securityandcompliance/v20210308:privateLinkServicesForSCCPowershell
azure-native:securityandcompliance:privateLinkServicesForEDMUpload
azure-native:securityandcompliance:privateLinkServicesForM365ComplianceCenter
azure-native:securityandcompliance:privateLinkServicesForM365SecurityCenter
azure-native:securityandcompliance:privateLinkServicesForMIPPolicySync
azure-native:securityandcompliance:privateLinkServicesForO365ManagementActivityAPI
azure-native:securityandcompliance:privateLinkServicesForSCCPowershell
azure-native:storagecache/v20230301preview:amlFilesystem
azure-native:synapse/v20210401preview:kustoPool
azure-native:synapse:kustoPool
azure-native:workloads/v20211201preview:monitor
azure-native:workloads/v20221101preview:monitor
azure-native:workloads/v20230401:monitor
azure-native:workloads:monitor
```

### Output of `pulumi about`

```
CLI          
Version      3.62.0
Go Version   go1.20.2
Go Compiler  gc

Host     
OS       debian
Version  11.6
Arch     x86_64
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by thomas11**
**Highly breaking - only merge for V2 release**

resolves #2365

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
Yeah, if aliases are case-sensitive (I suspect they are), we need to alias to old casing before we can ship this.

**Comment by thomas11** [comment]
@mikhailshilkov, @kpitzen Aliases are now added. Note that no change shows in the Go SDK because types were already title-cases there, presumably due to the Go visibility rules.

File: provider/pkg/gen/schema.go [hunk 1]
```diff
@@ -543,6 +540,18 @@ func (g *packageGenerator) genResourceVariant(prov string, apiSpec *openapi.Reso
 	module := g.providerToModule(prov)
 	swagger := resource.Swagger
 	path := resource.PathItem
+
+	var aliases []pschema.AliasSpec
+
+	// We want title-case type names. If the original name was lower-case, we add an alias.
```
Comment (mikhailshilkov) [inline provider/pkg/gen/schema.go:546]: We can add a note and/or open an issue to remove these aliases in 3.0

File: provider/pkg/gen/schema.go [hunk 2]
```diff
@@ -543,6 +540,18 @@ func (g *packageGenerator) genResourceVariant(prov string, apiSpec *openapi.Reso
...
+	canonicalTypeName := strings.Title(resource.typeName)
+	if canonicalTypeName != resource.typeName {
+		alias := fmt.Sprintf("%s:%s:%s", g.pkg.Name, module, resource.typeName)
+		aliases = append(aliases, pschema.AliasSpec{Type: &alias})
+		// Mutating input = bad but otherwise we risk inconsistent naming from downstream uses of resource.typeName.
+		resource.typeName = canonicalTypeName
```
Comment (mikhailshilkov) [inline provider/pkg/gen/schema.go:552]: Why have you switched away from changing `typeName` at the top of `genResources`? You could save a `legacyTypeName` before doing so and alias based on it, if you want to avoid mutation.

**Review by mikhailshilkov — COMMENTED** [review]
Left a few questions. What is our plan to ship this? We can't merge to master yet, right?

**Comment by thomas11** [comment]
> Left a few questions. What is our plan to ship this? We can't merge to master yet, right?

@mikhailshilkov No, we can't. Kyle and I were thinking of starting a V2 branch where we can merge such PRs and create pre-releases from.

File: provider/pkg/gen/schema.go [hunk 3]
```diff
@@ -543,6 +540,18 @@ func (g *packageGenerator) genResourceVariant(prov string, apiSpec *openapi.Reso
 	module := g.providerToModule(prov)
 	swagger := resource.Swagger
 	path := resource.PathItem
+
+	var aliases []pschema.AliasSpec
+
+	// We want title-case type names. If the original name was lower-case, we add an alias.
+	canonicalTypeName := strings.Title(resource.typeName)
+	if canonicalTypeName != resource.typeName {
+		alias := fmt.Sprintf("%s:%s:%s", g.pkg.Name, module, resource.typeName)
```
[the remark this answers is not in the document]
Comment (thomas11) [reply provider/pkg/gen/schema.go]: I think we should, come to think of it. I can't see a significant cost to doubling the number of aliases from what I know.

**Review by danielrbradley — APPROVED** [review]
This looks great!
