### PR TITLE
azcore fix: initialize request pipeline with configured cloud

### LINKED ISSUE #3795: New AzCore API Breaks Environment
### What happened?

Hello,

I was previously using `v2.60.0` of the Azure Native plugin with Azure Government with success but recently decided decided to bump up to the latest `v2.77.0` and noticed that all my CI builds were failing.
Image

I started investigating and found that in the `v2.71.0` release notes there is mention of a new AzCore backend for the API that has been enabled by default and it notes instructions to disable it to fall back to the previous implementation.
After finding that and disabling the new AzCore backend, my builds are working again.

It appears that the new AzCore API changes are not respecting the `ARM_ENVIRONMENT` / `azure-native:environment` settings as it is clearly dialing the Azure Commercial endpoints instead of the Government ones.

### Example

1. Use an Azure Government environment
2. Specify `azure-native:environment` in the Pulumi config for the stack
3. `pulumi up`
    - explosions.

### Output of `pulumi about`

Image

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by thomas11**
Fixes #3795, hopefully.

The way Azure's azcore and azidentity SDKs are designed makes it hard to test this, but reading [the source here](https://github.com/Azure/azure-sdk-for-go/blob/sdk/azcore/v1.16.0/sdk/azcore/arm/runtime/pipeline.go#L60) it looks like this change should fix the issue.

### CODE REVIEW

File: provider/pkg/azure/client_azcore.go [hunk 1]
```diff
@@ -49,7 +49,11 @@ func NewAzCoreClient(tokenCredential azcore.TokenCredential, userAgent string, a
 	})
 
 	if opts == nil {
-		opts = &arm.ClientOptions{}
+		opts = &arm.ClientOptions{
+			ClientOptions: policy.ClientOptions{
+				Cloud: azureCloud,
+			},
+		}
```
Comment (mjeffryes) [inline provider/pkg/azure/client_azcore.go:56]: is there no test we could add? At a minimum, it seems like we could extract out a "InitClientOptions" helper and add a unittest?

We should maybe add a comment too, pointing out why it's necessary to forward the `cloud.Configuration` via opts?

**Review by mjeffryes — APPROVED** [review]
Approving b/c I don't want to block you on timezone delta and it makes sense that this could fix the issue, but would be nice to capture this requirement in some sort of test or at least a comment.

File: provider/pkg/azure/client_azcore.go (hunk 1 above)
Comment (thomas11) [reply provider/pkg/azure/client_azcore.go:56]: I've extracted `InitClientOptions` and added a unit test for it, but that tests only the mechanics of the change, not that it fixes the user's problem. Still, additional coverage is always good.
