### PR TITLE
Fully support the OIDC token configuration

### LINKED ISSUE #2609: OIDC auth not working for GitLab
### What happened?

The [Azure Native OIDC docs page](https://www.pulumi.com/registry/packages/azure-native/installation-configuration/#oidc-pulumi-provider-configuration) give instructions for GitHub to Azure OIDC as if they were Git forge agnostic. Following its instructions for GitLab and setting the following environment variables results in auth error:

```console
 error: rpc error: code = Unknown desc = invocation of azure-native:authorization:getClientConfig returned an error: OIDC authentication was requested via useOidc/ARM_USE_OIDC but no token and/or request URL were configured.
```

`ARM_OIDC_REQUEST_TOKEN` is a GitHub Actions specific variable. For other CI systems, users need to use `ARM_OIDC_TOKEN`.See also [this GitHub issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/16901) and and Pulumi's [own docs page for AzAPI](https://www.pulumi.com/registry/packages/azapi/installation-configuration/). If I remove the GitHub Actions specific variables, `ARM_OIDC_REQUEST_TOKEN` and `ARM_OIDC_REQUEST_URL`, then set `ARM_OIDC_TOKEN` I still run into errors:

```console
 error: rpc error: code = Unknown desc = invocation of azure-native:authorization:getClientConfig returned an error: OIDC authentication was requested via useOidc/ARM_USE_OIDC but no token and/or request URL were configured.
```

I have verified I can log in independently to Azure in my GitLab CI step using [GitLab's native OIDC token fetching](https://docs.gitlab.com/ee/ci/secrets/id_token_authentication.html):

```.gitlab-ci.yml
image: gardendev/garden-azure:0.13.9-alpine-rootless

run-garden:
  stage: build
  id_tokens:
    ARM_OIDC_TOKEN
      aud: https://gitlab.hansen.agency
  script:
    - az login --service-principal -u $ARM_CLIENT_ID -t $ARM_TENANT_ID --federated-token $ARM_OIDC_TOKEN
    - garden workflow my-workflow --env=ci
```

### Expected Behavior

Pulumi's docs should provide Git forge agnostic doucmentation on setting up OIDC. OIDC should work without an `az login` pre-step. Azure Native OIDC should not attempt to use GitHub-specific functions when operating on other forges like GitLab, etc.

### Steps to reproduce

A reproducible Pulumi example is [available here](https://gitlab.hansen.agency/worldofgeese/little_bits_of_buddha/-/blob/19-split-microservices/terraform/Pulumi.yaml).

### Output of `pulumi about`

```
garden tools pulumi.pulumi-3-70-0 -- about
CLI          
Version      3.70.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME  VERSION
yaml  unknown

Host     
OS       clear-linux-os
Version  1
Arch     x86_64

This project is written in yaml

Current Stack: worldofgeese/azure-yaml/ci

Found no resources associated with ci

Found no pending operations associated with ci

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/worldofgeese
User           worldofgeese
Organizations  worldofgeese

No dependencies found
```

### Additional context

Logging in with `az login` is unexpectedly a pre-condition for getting this far, else I receive a different auth error:

```console
                  type: runtime
                  stack: |-
                    Error: Error when applying pulumi stack:
                    Previewing update (ci)
                    View Live: https://app.pulumi.com/worldofgeese/azure-yaml/ci/previews/38c53092-5802-4cbf-9813-637ac7b603aa
                     +  pulumi:pulumi:Stack azure-yaml-ci create 
                    @ Previewing update...............
                        pulumi:providers:azuread default  error: rpc error: code = Unknown desc = failed to load Azure credentials.
                     +  pulumi:pulumi:Stack azure-yaml-ci create 
                        pulumi:providers:azuread default  1 error
                    Diagnostics:
                      pulumi:providers:azuread (default):
                        error: rpc error: code = Unknown desc = failed to load Azure credentials.
                        Details: could not configure AzureCli Authorizer: obtaining subscription ID: running Azure CLI: exit status 1: ERROR: Please run 'az login' to setup account.
                        
                        	Please make sure you have signed in via 'az login' or configured another authentication method.
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #2884: [OIDC] Can't use federated credentials in Azure DevOps
### What happened?

Azure DevOps provides three variables to connect to Azure using OIDC, as documented in the [AzureCLI task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines):

* tenantId
* servicePrincipalId
* idToken

Note that there's no URL like in GitHub.

I tried to follow [this example](https://devblogs.microsoft.com/devops/public-preview-of-workload-identity-federation-for-azure-pipelines/) by Azure where they demonstrate the OIDC authentication with Terraform. In the example, they only specify `ARM_OIDC_TOKEN` and omit `ARM_OIDC_REQUEST_TOKEN` and `ARM_OIDC_REQUEST_URL`. When I do the same with Pulumi, it crashes with the following error message:

```
error: OIDC authentication was requested via useOidc/ARM_USE_OIDC but no token and/or
request URL were configured. See
https://www.pulumi.com/registry/packages/azure-native/installation-configuration/#credentials for more information.
```

The error gets thrown [in this line](https://github.com/pulumi/pulumi-azure-native/blob/951c3ef92fc5e28f3f12fe3a77fdde3784905396/provider/pkg/provider/auth.go#L60C54-L60C54) because the Pulumi provider requires both the request URL and the request token to be set.

After looking through the [code of the Terraform AzureRM provider](https://github.com/hashicorp/terraform-provider-azurerm/blob/640e4acd895e3802368746a8d947c55fa19e6c62/internal/provider/provider.go#L435) it seems to me that `ARM_OIDC_REQUEST_TOKEN` and `ARM_OIDC_REQUEST_URL` are used for some GitHub specific code, while the `ARM_OIDC_TOKEN` is used in cases where the token can be resolved through Azure AD directly (?).

I believe that the azure-native provider should **not** throw an error if _either_

* both `ARM_OIDC_REQUEST_TOKEN` and `ARM_OIDC_REQUEST_URL` are set _or_
* `ARM_OIDC_TOKEN` is set

### Example

1. Create a new Azure service connection in Azure DevOps that uses federated credentials
2. Add a Pulumi stack to your project
3. Add a pipeline to your project and add the following task:

```yaml
- task: AzureCLI@2
  displayName: "Pulumi up"
  inputs:
    azureSubscription: <service connection with federated credential>
    scriptType: bash
    scriptLocation: inlineScript
    addSpnToEnvironment: true
    inlineScript: |
      export ARM_USE_OIDC=true
      export ARM_TENANT_ID="$tenantId"
      export ARM_CLIENT_ID="$servicePrincipalId"
      export ARM_OIDC_TOKEN="$idToken"
      export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
      
      pulumi up --yes --diff
```

### Output of `pulumi about`

```
CLI          
Version      3.91.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.17.0
dotnet        unknown
kubernetes    4.5.4

Host     
OS       darwin
Version  14.1
Arch     arm64

This project is written in dotnet: executable='/usr/local/share/dotnet/dotnet' version='7.0.203'

Backend        
Name           ...
URL            azblob://pulumi-backend
User           ...
Organizations  
Token type     personal

Dependencies:
NAME                VERSION
Pulumi              3.58.0
Pulumi.AzureNative  2.17.0
Pulumi.Kubernetes   4.5.4
```

### Additional context

Possibly related to #2868 and/or https://github.com/pulumi/pulumi/issues/14509

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #2885: [OIDC] Expose OidcToken in the explicit provider arguments
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

#2873/#2874 exposed some OIDC arguments in the ProviderArgs.

To be able to create our own providers that are compatible with Azure DevOps (#2884), we need the `OidcToken` argument as well.

### PR DESCRIPTION
**Pull request by thomas11**
This PRs remediates an oversight regarding OIDC configuration.

On GitHub, a token exchange local to GitHub happens first where an internal GitHub token is exchanged for an OIDC token from GitHub. This exchange is what's configured via `oidcRequestToken`/`ARM_OIDC_REQUEST_TOKEN` and `oidcRequestUrl`/`ARM_OIDC_REQUEST_URL`.

However, on other providers such as Azure and GitLab, a ready-to-use OIDC token is provided. This is configured via the single config `oidcToken`/`ARM_OIDC_TOKEN`. But that failed this provider's check for valid configuration, which this PR fixes.

Resolves #2884 
Resolves #2885
May also fix #2609, to be tested.

Commits:
- Upgrade auth deps as far as possible - further requires migrating to hashicorp/go-azure-sdk
- Support OIDC tokens directly, refactor and unit test
- Explicit provider argument for OIDC token

### CODE REVIEW

**Comment by moredatapls** [comment]
Thank you so much for working on this so quickly @thomas11!

File: provider/pkg/provider/auth_test.go [hunk 1]
```diff
@@ -31,3 +31,88 @@ func TestAcceptedAzVersions(t *testing.T) {
...
+	conf, err := p.determineOidcConfig()
+	assert.Nil(t, err)
+	assert.Equal(t, "t1", conf.oidcRequestToken)
+	assert.Equal(t, "url1", conf.oidcRequestUrl)
+	assert.Empty(t, conf.oidcToken)
+}
+
+func TestOidcConfigWithRequestUrlFromConfig(t *testing.T) {
+	p := azureNativeProvider{
+		config: map[string]string{
```
Comment (moredatapls) [inline provider/pkg/provider/auth_test.go:64]: what should happen if all three values (oidcToken, oidcRequestToken, oidcRequestUrl) are set?

Comment (moredatapls) [reply provider/pkg/provider/auth_test.go:64]: Not sure when this would happen, but if this is an unsupported case, would it make sense to return some error message?

Comment (thomas11) [reply provider/pkg/provider/auth_test.go:64]: That's a good point but I think it's ok for now. It is actually a supported configuration, except the request token and request URL will be ignored. That might make sense in certain scenarios on GitHub where the user doesn't want to use the standard GH-provided token. Not sure when that would make sense but I don't want to block it, either.

Comment (thomas11) [reply provider/pkg/provider/auth_test.go:64]: P.S. I'm planning to update [the docs](https://www.pulumi.com/registry/packages/azure-native/installation-configuration/#authenticate-with-openid-connect-oidc) to make the OIDC part clearer, and will add this as well.

Comment (moredatapls) [reply provider/pkg/provider/auth_test.go:64]: ok, thanks

**Review by danielrbradley — APPROVED** [review]
