### PR TITLE
Avoid provider credentials leaking into state

### LINKED ISSUE #1309: Custom providers can leak credentials to state file from environment variables
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
If you store the credentials in environment variables (`ARM_CLIENT_ID`, `ARM_CLIENT_SECRET`, `ARM_SUBSCRIPTION_ID`, `ARM_TENANT_ID`) and use an explicit provider (even if the provider doesn't include the credentials, then the contents of the environment variables are written to the state in plain text.

**Steps to reproduce:**

Code:

```typescript
const provider = new azure.Provider("provider", {
    environment: "public"
})

// Create an Azure Resource Group
const vnet = new network.VirtualNetwork("vnet", {
    resourceGroupName: resourcegroup.name,
    addressSpace: {
        addressPrefixes: ["10.0.0.0/16"],
    },
}, { provider })
```
and run the following:

`export ARM_CLIENT_ID=CCCC && export ARM_CLIENT_SECRET=XXXX && export ARM_SUBSCRIPTION_ID=YYY && export ARM_TENANT_ID=ZZZZ && pulumi up` 

then in the stack you get the following:

```json
{
  "urn": "urn:pulumi:dev::using-azure-creds::pulumi:providers:azure-native::provider",
  "custom": true,
  "id": "b7ec06bb-7661-4702-bb47-b3799e9e67c2",
  "type": "pulumi:providers:azure-native",
  "inputs": {
    "clientId": "CCCC",
    "clientSecret": "XXXX",
    "environment": "public",
    "subscriptionId": "YYY",
    "tenantId": "ZZZZ",
    "useMsi": "false",
    "version": "1.46.0"
  },
  "outputs": {
    "clientId": "CCCC",
    "clientSecret": "XXXX,
    "environment": "public",
    "subscriptionId": "YYY",
    "tenantId": "ZZZZ",
    "useMsi": "false",
    "version": "1.46.0"
  },
  "parent": "urn:pulumi:dev::using-azure-creds::pulumi:pulumi:Stack::using-azure-creds-dev",
  "propertyDependencies": {
    "clientId": null,
    "clientSecret": null,
    "environment": null,
    "subscriptionId": null,
    "tenantId": null,
    "useMsi": null
  }
}

```

### PR DESCRIPTION
**Pull request by viveklak**
I have validated that upgrading the provider version and running a `pulumi up` overwrites the state correctly. With the additional secrets, the state is still secure even if they are explicitly entered as inputs.

Fixes #1309

### CODE REVIEW

File: provider/pkg/gen/schema.go [hunk 1]
```diff
@@ -109,109 +116,60 @@ func PulumiSchema(providerMap openapi.AzureProviders) (*pschema.PackageSpec, *re
 			},
 			InputProperties: map[string]pschema.PropertySpec{
 				"subscriptionId": {
-					TypeSpec: pschema.TypeSpec{Type: "string"},
-					DefaultInfo: &pschema.DefaultSpec{
-						Environment: []string{
-							"ARM_SUBSCRIPTION_ID",
-						},
-					},
```
Comment (lblackstone) [inline provider/pkg/gen/schema.go:117]: This doesn't seem right. We still want to support reading configuration from env vars, but this change prevents that. It also has the side effect of removing these env vars from the API docs.

File: provider/pkg/gen/schema.go [hunk 2]
```diff
@@ -55,21 +55,26 @@ func PulumiSchema(providerMap openapi.AzureProviders) (*pschema.PackageSpec, *re
 				"subscriptionId": {
 					TypeSpec:    pschema.TypeSpec{Type: "string"},
 					Description: "The Subscription ID which should be used.",
+					Secret:      true,
```
Comment (lblackstone) [inline provider/pkg/gen/schema.go:58]: Is the `subscriptionId` considered sensitive? Same question for `clientId`, `tenantId`, and `auxiliaryTenantIds`. It seems useful to have the ids present in diffs, etc., so I'd suggest leaving them as is unless there's clear documentation to the contrary.

Comment (mikhailshilkov) [reply provider/pkg/gen/schema.go:58]: I think `tenantId` is publicly discoverable if there's a public DNS name in it or something like that. It's not a secret.
Subscription ID is likely not a secret either as there isn't much one can do with it https://stackoverflow.com/questions/45661109/are-azure-subscription-id-aad-tenant-id-and-aad-app-client-id-considered-secre
If it reduces preview quality, we should definitely leave it as open.

File: provider/pkg/gen/schema.go (hunk 1 above)
Comment (mikhailshilkov) [reply provider/pkg/gen/schema.go:117]: I think this is motivated by https://github.com/pulumi/pulumi-azure/pull/583

**Comment by mikhailshilkov** [comment]
I don't feel great about changing too much here. As a P0 fix, I would copy verbatim the configuration from Azure Classic (if that's possible) and make sure the issue is fixed. We could discuss further improvements separately.

File: provider/pkg/gen/schema.go (hunk 1 above)
Comment (viveklak) [reply provider/pkg/gen/schema.go:117]: As mikhail mentioned this is for parity with https://github.com/pulumi/pulumi-azure/pull/583. I can re-add this and other non-sensitive fields if desired.
FWIW we read the configuration from the environment variable anyway in the provider: https://github.com/pulumi/pulumi-azure-native/blob/master/provider/pkg/provider/provider.go#L1637. The use of DefaultInfo obviates the need to do so - but it comes with the penalty that creating a provider through the SDK causes the subscriptionId to be pre-populated from the environment variable (causing them to be embedded in the state).

An alternative here is to (optionally?) change the semantics of DefaultInfo to not generate the environment variable lookup code in the SDK (the provider would have to do the lookup instead) but retain the API docs support. cc @pgavlin for thoughts here. However, that will have to happen outside the context of this change.

File: provider/pkg/gen/schema.go (hunk 2 above)
Comment (viveklak) [reply provider/pkg/gen/schema.go:58]: Thank you. I wasn't sure on what parts are deemed sensitive. I am currently making a change to only mark clientId, clientSecret, clientCertificatePassword as secrets.

**Comment by viveklak** [comment]
> 

OK - I still think we need the 3 fields to be secrets. Setting them explicitly through the SDK constructor still leaks them into state otherwise. Other than that we should be very close to the change in https://github.com/pulumi/pulumi-azure/pull/583

**Comment by viveklak** [comment]
> I don't feel great about changing too much here. As a P0 fix, I would copy verbatim the configuration from Azure Classic (if that's possible) and make sure the issue is fixed. We could discuss further improvements separately.

OK - I still think we need the 3 fields to be secrets. Setting them explicitly through the SDK constructor still leaks them into state otherwise. Other than that we should be very close to the change in pulumi/pulumi-azure#583

**Comment by viveklak** [comment]
This is ready for review. I validated that upgrading the provider version and running a `pulumi up` overwrites the state correctly. With the additional secrets, the state is still secure even if they are explicitly entered.

**Comment by viveklak** [comment]
I will follow-up the changelog with instructions to rotate any secrets associated after the update.

File: provider/pkg/gen/schema.go (hunk 1 above)
Comment (viveklak) [reply provider/pkg/gen/schema.go:117]: I suggest I followup with a docs change to add the environment variable documentation overlay. Would like to release this change ASAP.

**Review by lblackstone — APPROVED** [review]
