### PR TITLE
Fix flaky TestAccSimpleTs test

### LINKED ISSUE #3813: Integration test TestAccSimpleTs is flaky
```
gh flaky -workflows release,master,acceptance-test,autorest-scheduled
Running as thomas11

Checking last 100 runs of the last 14 days of workflows:
    {2576859 release .github/workflows/release.yml}
    {2342475 master .github/workflows/master.yml}
    {46530939 acceptance-test .github/workflows/acceptance-test.yml}
    {127814901 autorest-scheduled .github/workflows/autorest-scheduled.yml}
Starting search from 2024-12-09

Found 0 runs with retries (out of 2) for workflow 'release'

Found 3 runs with retries (out of 20) for workflow 'master'
Checking failed attempts: ...

Found 1 runs with retries (out of 82) for workflow 'acceptance-test'
Checking failed attempts: .

Found 4 runs with retries (out of 13) for workflow 'autorest-scheduled'
Checking failed attempts: ....

Examined 117 workflow runs, out of which 8 succeeded after retries.
Found 8 failed jobs, out of which 8 had logs available.
Failed tests by finder: map[Gotestfmt:0 Plain Go:8]

Note: append the failed job URL suffixes to 'https://github.com/pulumi/pulumi-azure-native/actions/runs/'.

Failures  Test             Failed jobs
6         TestAccSimpleTs  12319625744/job/34388101906, 12420208944/job/34678091864, 12460662563/job/34779655418, 12405659040/job/34633435748, 12365771126/job/34511973802, 12289257385/job/34294999012
```

### PR DESCRIPTION
**Pull request by thomas11**
Hopefully fix the very flaky test TestAccSimpleTs. Fixes #3813.

I ran this version of the test in a loop and it succeeded 16 times in a row (each run is 5-6 minutes).

Commits are logically separate:
- **Update examples to latest p/p**
- **Show diff when test fails preview**
- **WebAppSlot bugfix: look up correct resource. Most likely had no impact.**
- **Update ignoreChanges for siteConfig in WebApp/WebAppSlot to ensure proper handling of site configuration during refresh-update cycles.**

### CODE REVIEW

File: examples/simple/index.ts [hunk 1]
```diff
@@ -122,8 +122,7 @@ const appService = new web.WebApp("app", {
     },
 // Subnet is associated by WebAppSwiftVirtualNetworkConnection below, so it should be ignored here to avoid
 // overrides on refresh-update cycles.
-// SiteConfig is modified outside of this resource via the WebApp* resources.
-}, { ignoreChanges: ["virtualNetworkSubnetId", "siteConfig", "siteConfig.*"] });
+}, { ignoreChanges: ["siteConfig.vnetName", "virtualNetworkSubnetId"] });
```
Comment (mjeffryes) [inline examples/simple/index.ts:125]: can we preserve some comment on `siteConfig.vnetName` too?

**Review by mjeffryes — APPROVED** [review]
LGTM

File: examples/simple/index.ts (hunk 1 above)
Comment (thomas11) [reply examples/simple/index.ts:125]: I was under the impression the comment "Subnet is associated ..." covers it. It's the same vnet, no?

Comment (mjeffryes) [reply examples/simple/index.ts:125]: I suppose that's fair. Coming in with 0 context on the resource "virtualNetworkSubnetId" explicitly is about a subnet, whereas "siteConfig.vnetName" is just talking about a vnet and in the general case the can be more than one subnet in a vnet right? No strong opinion here though if it's generally clear when working with WebApp resources.
