### PR TITLE
Redact the (fake) AWS access key id in an Azure example that blocks GH pushes

### LINKED ISSUE #3164: Workflow failure: nightly-sdk-generation
## Workflow Failure

[nightly-sdk-generation](https://github.com/pulumi/pulumi-azure-native/blob/master/.github/workflows/nightly-sdk-generation.yml) has failed. See the list of failures below:

- [2024-03-21T04:55:19.000Z](https://github.com/pulumi/pulumi-azure-native/actions/runs/8369763158)

- [2024-03-22T04:55:09.000Z](https://github.com/pulumi/pulumi-azure-native/actions/runs/8385554520)

### LINKED ISSUE #3166: Workflow failure: weekly-pulumi-update
## Workflow Failure

[weekly-pulumi-update](https://github.com/pulumi/pulumi-azure-native/blob/master/.github/workflows/weekly-pulumi-update.yml) has failed. See the list of failures below:

- [2024-03-21T12:58:30.000Z](https://github.com/pulumi/pulumi-azure-native/actions/runs/8375101189)

### PR DESCRIPTION
**Pull request by thomas11**
The Azure spec example [CreateUpdateAwsCredConnectorSubscription](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/security/resource-manager/Microsoft.Security/preview/2020-01-01-preview/examples/Connectors/CreateUpdateAwsCredConnectorSubscription_example.json#L23) contains a probably fake, but real looking AWS Access Key id. It hasn't been modified in years, but it seems GitHub expanded their secrets scanning, because now our schema.json containing this example is refused:
```
remote: - GITHUB PUSH PROTECTION        
remote:   ——————————————————————————————————————————————————————        
remote:    Resolve the following secrets before pushing again.        
remote:           
remote:    (?) Learn how to resolve a blocked push        
remote:    https://docs.github.com/code-security/secret-scanning/pushing-a-branch-blocked-by-push-protection        
remote:           
remote:           
remote:   —— Amazon AWS Access Key ID ——————————————————————————        
remote:    locations:        
remote:      - commit: f1b05bccccfa232413de3e74d1c34c189e536117        
remote:        path: provider/cmd/pulumi-resource-azure-native/schema.json:652276        
remote:      - commit: f1b05bccccfa232413de3e74d1c34c189e536117        
remote:        path: provider/cmd/pulumi-resource-azure-native/schema.json:652276        
remote:      - commit: f1b05bccccfa232413de3e74d1c34c189e536117        
remote:        path: provider/cmd/pulumi-resource-azure-native/schema.json:652276        
remote:      - commit: f1b05bccccfa232413de3e74d1c34c189e536117        
remote:        path: provider/cmd/pulumi-resource-azure-native/schema.json:652276        
remote:      - commit: f1b05bccccfa232413de3e74d1c34c189e536117        
remote:        path: provider/cmd/pulumi-resource-azure-native/schema.json:652276 
```

This blocks both developer PRs and automated upgrades.

I first thought of excluding the offending API version, but it's the only one containing this resource.

Instead, this PR redacts the key id from the example before we process it further. That way, we keep both the resource and the example.

I've also filed an [upstream issue](https://github.com/Azure/azure-rest-api-specs/issues/28404).

Fixes #3164 
Fixes #3166

### CODE REVIEW

**Review by danielrbradley — APPROVED** [review]
Looks reasonable. Shame to have to special-case this in the code, but something like scanning for all fields named "awsAccessKeyId" is likely much more complex and this is a pretty special one-off case it seems.

File: provider/pkg/util/data_structures_test.go [hunk 1]
```diff
@@ -0,0 +1,57 @@
+package util
+
+import (
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+)
+
+func TestGetInnerMap(t *testing.T) {
```
Comment (mjeffryes) [inline provider/pkg/util/data_structures_test.go:9]: kudos for adding a test while you were here!
