### PR TITLE
Fix SQL Retention Policies' default state

### LINKED ISSUE #1203: Sql resources destroy actions fail very badly
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I have a ComponentResource of sql server with a sql pool and some databases. The databases have retention policies.
Parents are setup like:
* longterm retentionpolicies -> db
* shortterm retentionpolicies -> db
* db -> sql server
* pool -> sql server
* sql server -> resource group

When I run a destroy targeting the sql server urn I get the following errors

image

So these policies are not deleted but when I run the command again I'm greeted with the mention that my target couldn't be found in my stack

### Steps to reproduce

1. create resource hierarchy as described above (rg -> sql server -> db -> retention policy)
2. pulumi up (resources are created)
3. pulumi destroy --target sqlserverUrn --target-depend (see failures happening)
4. try again

Expected: Resources to be removed and no corruption in my state if something did not happen.
Actual: Resources where not removed and I lost track of my resources in the state which where not actually deleted.

### LINKED ISSUE #1345: Unable to delete `SQL.BackupShortTermRetentionPolicy`
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

It appears the Azure Native provider is unable to delete `SQL.BackupShortTermRetentionPolicy` resource. The deployment of such resource work as expected and no errors are reported. However, calling `pulumi destroy` yields an error and an early termination of the command.

```
Diagnostics:
  azure-native:sql:BackupShortTermRetentionPolicy (bkpTestdb):
    error: Code="InvalidParameterValue" Message="Invalid value given for parameter properties. Specify a valid parameter value."
 
  pulumi:pulumi:Stack (azn-cs-sql-dev):
    error: update failed
```

Calling `pulumi refresh` doesn't show any changes or missing resources.

### Notes

Could it be an ARM issue given this has a very similar error message? 

* https://stackoverflow.com/questions/51929215/create-sql-server-via-azure-resource-manager-arm-template
* https://github.com/hashicorp/terraform-provider-azurerm/issues/10513

### Steps to reproduce

1. Create a new Azure Stack in WestUS2 with the sample code attached below
2. Run `pulumi up` to deploy the resources
3. Check the Azure Console that all the declared resources are present
4. Run `pulumi destroy` and observe the error

#### `SimpleStack.cs`
```cs
using Pulumi;
using Pulumi.AzureNative.Resources;
using SQL = Pulumi.AzureNative.Sql;

public class SimpleStack : Stack
{
    public string Location = "WestUS2";
    public string ResourceGroupName = "RGTest1";
    public string SqlServerName = "SCDevServer";

    public SimpleStack()
    {
        var resourceGroupArgs = new ResourceGroupArgs
        {
            Location = this.Location,
            ResourceGroupName = this.ResourceGroupName
        };
        var resourceGroup = new ResourceGroup(ResourceGroupName, resourceGroupArgs);

        var sqlServer = new SQL.Server(SqlServerName, new SQL.ServerArgs
        {
            ServerName = SqlServerName,
            ResourceGroupName = resourceGroup.Name,
            AdministratorLogin = "AdminUser",
            AdministratorLoginPassword = "Test1234!@",
            Version = "12.0",
            Location = Location,
            MinimalTlsVersion = "1.2",
            PublicNetworkAccess = "Disabled",
        });

        var poolSku = new SQL.Inputs.SkuArgs
        {
            Name = "StandardPool",
            Capacity = 100,
            Size = "Standard"
        };
        var perDbArgs = new SQL.Inputs.ElasticPoolPerDatabaseSettingsArgs
        {
            MaxCapacity = 100,
            MinCapacity = 0
        };

        var elasticPoolArgs = new SQL.ElasticPoolArgs
        {
            ElasticPoolName = "SCTestPool1",
            Location = this.Location,
            ResourceGroupName = resourceGroup.Name,
            ServerName = sqlServer.Name,
            Sku = poolSku,
            MaxSizeBytes = 107374182400,
            ZoneRedundant = false,
            PerDatabaseSettings = perDbArgs
        };

        var elasticPool = new SQL.ElasticPool("SCTestPool1", elasticPoolArgs);

        var args = new SQL.DatabaseArgs
        {
            ResourceGroupName = resourceGroup.Name,
            DatabaseName = "testdb",
            ServerName = sqlServer.Name,
            Location = this.Location,
            ElasticPoolId = elasticPool.Id,
        };
        var newdb = new SQL.Database("testdb", args);

        var retentionArgs = new SQL.BackupShortTermRetentionPolicyArgs
        {
            DatabaseName = newdb.Name,
            PolicyName = "default",
            ResourceGroupName = resourceGroup.Name,
            RetentionDays = 30,
            ServerName = sqlServer.Name,
        };

        var bkpPolicy = new SQL.BackupShortTermRetentionPolicy("bkpTestdb", retentionArgs);
    }
}
```

I've also run the command in debug ([debugs.txt](https://github.com/pulumi/pulumi-azure-native/files/7664145/debugs.txt)) and the error is also shown on the Azure console

image

Expected: The stack is correctly destroyed.
Actual: An error occurs and the stack destruction is interrupted.

### PR DESCRIPTION
**Pull request by mikhailshilkov**
Fix #1345
Fix #1203

### CODE REVIEW

File: provider/pkg/openapi/defaultResourcesState.go [hunk 1]
```diff
@@ -53,8 +53,15 @@ var defaultResourcesStateRaw = map[string]map[string]interface{}{
 	"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/auditingSettings/{blobAuditingPolicyName}": {
 		"state": "Disabled",
 	},
-	"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/backupLongTermRetentionPolicies/{policyName}":  {},
-	"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/backupShortTermRetentionPolicies/{policyName}": {},
+	"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/backupLongTermRetentionPolicies/{policyName}":  {
+		"weeklyRetention": "PT0S",
+		"monthlyRetention":"PT0S",
+		"yearlyRetention": "PT0S",
+		"weekOfYear":      1,
```
Comment (lblackstone) [inline provider/pkg/openapi/defaultResourcesState.go:60]: Do you have a link to docs for these default values?

**Review by lblackstone — APPROVED** [review]
Changes LGTM -- just one clarifying question

File: provider/pkg/openapi/defaultResourcesState.go (hunk 1 above)
Comment (mikhailshilkov) [reply provider/pkg/openapi/defaultResourcesState.go:60]: I don't. I calculated these by observing the actual state of a newly created SQL database.
