### PR TITLE
Capture and correct type case conflicts

### LINKED ISSUE #2796: Nightly generation failure
Started failing on the 28th September:

- https://github.com/pulumi/pulumi-azure-native/actions/runs/6334683391/job/17204811882?pr=2780

PR is generated but the dotnet SDK fails to build:

```
Error: /home/runner/work/pulumi-azure-native/pulumi-azure-native/sdk/dotnet/ServiceFabric/V20230901Preview/GetManagedCluster.cs(175,48): error CS0234: The type or namespace name 'IPTagResponse' does not exist in the namespace 'Pulumi.AzureNative.ServiceFabric.V20230901Preview.Outputs' (are you missing an assembly reference?) [/home/runner/work/pulumi-azure-native/pulumi-azure-native/sdk/dotnet/Pulumi.AzureNative.csproj]
Error: /home/runner/work/pulumi-azure-native/pulumi-azure-native/sdk/dotnet/ServiceFabric/V20230901Preview/GetManagedCluster.cs(297,36): error CS0234: The type or namespace name 'IPTagResponse' does not exist in the namespace 'Pulumi.AzureNative.ServiceFabric.V20230901Preview.Outputs' (are you missing an assembly reference?) [/home/runner/work/pulumi-azure-native/pulumi-azure-native/sdk/dotnet/Pulumi.AzureNative.csproj]
Error: /home/runner/work/pulumi-azure-native/pulumi-azure-native/sdk/dotnet/ServiceFabric/V20230901Preview/Inputs/IpConfigurationPublicIPAddressConfigurationArgs.cs(24,33): error CS0234: The type or namespace name 'IpTagArgs' does not exist in the namespace 'Pulumi.AzureNative.ServiceFabric.V20230901Preview.Inputs' (are you missing an assembly reference?) [/home/runner/work/pulumi-azure-native/pulumi-azure-native/sdk/dotnet/Pulumi.AzureNative.csproj]
Error: /home/runner/work/pulumi-azure-native/pulumi-azure-native/sdk/dotnet/ServiceFabric/V20230901Preview/Inputs/IpConfigurationPublicIPAddressConfigurationArgs.cs(19,34): error CS0234: The type or namespace name 'IpTagArgs' does not exist in the namespace 'Pulumi.AzureNative.ServiceFabric.V20230901Preview.Inputs' (are you missing an assembly reference?) [/home/runner/work/pulumi-azure-native/pulumi-azure-native/sdk/dotnet/Pulumi.AzureNative.csproj]
Error: /home/runner/work/pulumi-azure-native/pulumi-azure-native/sdk/dotnet/ServiceFabric/V20230901Preview/ManagedCluster.cs(166,46): error CS0234: The type or namespace name 'IPTagResponse' does not exist in the namespace 'Pulumi.AzureNative.ServiceFabric.V20230901Preview.Outputs' (are you missing an assembly reference?) [/home/runner/work/pulumi-azure-native/pulumi-azure-native/sdk/dotnet/Pulumi.AzureNative.csproj]
```

This has been caused by the addition of a new ServiceFabric version: https://github.com/Azure/azure-rest-api-specs/pull/25779.

> This version introduces two versions of the IP Tag definition - in nodetype.json and managedcluster.json.
> In managedcluster.json it's named #/definitions/IPTag.
> In nodetype.json it's named #/definitions/IpTag.

Have notified upstream to the issue, but we'll likely need to normalize this our side too.

### PR DESCRIPTION
**Pull request by danielrbradley**
1. Introduce a type for normalising case sensitive tokens. This just uses the first variant it sees.
2. Declare this collection globally and pass down into each module generation.
3. Normalise the type token before visiting and generating each type.
4. Add report to list any time we change the case of a type.

Fixes #2796 

Tested locally having rebased on top of latest nightly branch.

### CODE REVIEW

**Comment by danielrbradley** [comment]
Ideally we should also address this with resources and functions too as they can both have the same issue in theory. Arguably, we should just have a better package building library which has this integrated directly.

File: provider/pkg/gen/schema.go [hunk 1]
```diff
@@ -1034,6 +1041,60 @@ func getResponseSchema(ctx *openapi.ReferenceContext, statusCodeResponses map[in
 	return nil, nil
 }
 
+type caseSensitiveTokens struct {
+	typesLowered map[string][]string
```
Comment (iwahbe) [inline provider/pkg/gen/schema.go:1045]: I read this as:
```go
map[case-insensitive-token][canonicalized-token, ...other-tokens]
```
Is that right?

File: provider/pkg/gen/schema.go [hunk 2]
```diff
@@ -1034,6 +1041,60 @@ func getResponseSchema(ctx *openapi.ReferenceContext, statusCodeResponses map[in
...
+}
+
+func NewCaseSensitiveTokens() caseSensitiveTokens {
```
Comment (iwahbe) [inline provider/pkg/gen/schema.go:1048]: We have an exported function returning a private type. Unless there is a pressing reason not too, can we choose if this will be public or private?

It looks like private is possible so I would default to that.

File: provider/pkg/gen/schema.go [hunk 3]
```diff
@@ -1034,6 +1041,60 @@ func getResponseSchema(ctx *openapi.ReferenceContext, statusCodeResponses map[in
...
+	conflicts := make(map[string][]string)
+	for _, caseVariants := range v.typesLowered {
+		if len(caseVariants) > 1 {
+			conflicts[caseVariants[0]] = caseVariants[1:]
+		}
+	}
+	return conflicts
+}
+
+func (c CaseConflicts) ToWarnings() []string {
```
Comment (iwahbe) [inline provider/pkg/gen/schema.go:1089]: I don't see where this is called. Is it part of an interface? If so, a `var _ = (TheInterface)((CaseConflicts)(nil)` would be appreciated.

File: provider/pkg/gen/schema.go (hunk 1 above)
Comment (danielrbradley) [reply provider/pkg/gen/schema.go:1045]: Yup - that's the internal type.

File: provider/pkg/gen/schema.go (hunk 3 above)
Comment (danielrbradley) [reply provider/pkg/gen/schema.go:1089]: Oh yup - an earlier implementation detail that got lost in the rebase. Will delete.

File: provider/pkg/gen/schema.go [hunk 4]
```diff
@@ -1034,6 +1041,51 @@ func getResponseSchema(ctx *openapi.ReferenceContext, statusCodeResponses map[in
 	return nil, nil
 }
 
+type caseSensitiveTokens struct {
+	typesLowered map[string][]string
```
Comment (thomas11) [inline provider/pkg/gen/schema.go:1045]: The naming of types vs tokens is a bit mixed up here

File: provider/pkg/gen/schema.go [hunk 5]
```diff
@@ -1034,6 +1041,51 @@ func getResponseSchema(ctx *openapi.ReferenceContext, statusCodeResponses map[in
...
+}
+
+func newCaseSensitiveTokens() caseSensitiveTokens {
+	return caseSensitiveTokens{typesLowered: make(map[string][]string)}
+}
+
+// normalizeTokenCase returns the normalized token.
+// This normalizes all casing to the first seen casing. For this to be consistent,
+// we rely on iterating all specs in the same order each time.
+func (v *caseSensitiveTokens) normalizeTokenCase(token string) string {
```
Comment (thomas11) [inline provider/pkg/gen/schema.go:1055]: `v`?

**Review by thomas11 — APPROVED** [review]
LGTM, just more naming nits :)

File: provider/pkg/gen/schema.go (hunk 5 above)
Comment (danielrbradley) [reply provider/pkg/gen/schema.go]: Originally this was called visitedTypes. Have updated.
